### DISCUSSION TITLE
Trouble with config file

### DISCUSSION THREAD

**Discussion by nnnik** [distribution/distribution#4484] [Q&A] [answered]
Hey I mounted a config file in accordance with the docs at: https://distribution.github.io/distribution/about/configuration/
The docker-compose file looks something like this:
```yaml
services:
  registry:
    image: registry:2.7
    container_name: registry
    user: ***:***
    restart: always
    volumes:
      - ***:/data
      - ./config.yml:/etc/distribution/config.yml:
      - ./.htpasswd:/.htpasswd:
    ports:
      - 5000:5000
    deploy:
      resources:
        limits:
          memory: 500M
```
The file also ends up in the docker at that spot - however the settings within that file do not seem to take any effect:
(I know that htpasswd is only useful if TLS is enabled - ...)
```yaml
version: 0.1
log:
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /data
  tag:
    concurrencylimit: 4
http:
  addr: :5000
  net: tcp
  secret: ***
  headers:
    X-Content-Type-Options: [nosniff]
auth:
  htpasswd:
    realm: basic-realm
    path: /.htpasswd
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```
However when I launch the docker-compose file it reports:
```
registry  | time="2024-10-13T09:28:19.401262538Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.11.2 instance.id=d50d8473-5632-42bc-9772-15cde463d8cb service=registry version=v2.7.1 
registry  | time="2024-10-13T09:28:19.401479444Z" level=info msg="Starting upload purge in 42m0s" go.version=go1.11.2 instance.id=d50d8473-5632-42bc-9772-15cde463d8cb service=registry version=v2.7.1 
registry  | time="2024-10-13T09:28:19.401525906Z" level=info msg="redis not configured" go.version=go1.11.2 instance.id=d50d8473-5632-42bc-9772-15cde463d8cb service=registry version=v2.7.1 
registry  | time="2024-10-13T09:28:19.430580749Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.11.2 instance.id=d50d8473-5632-42bc-9772-15cde463d8cb service=registry version=v2.7.1 
registry  | time="2024-10-13T09:28:19.430912116Z" level=info msg="listening on [::]:5000" go.version=go1.11.2 instance.id=d50d8473-5632-42bc-9772-15cde463d8cb service=registry version=v2.7.1
```
I tried with multiple tags (Which ended up being the Versions 2.8 and 2.7) both of which yielded similar results.
I then went and tried to track where the loading of the yaml file happens in the source code.
I got to https://github.com/distribution/distribution/blob/release/2.8/configuration/configuration.go#L662C6-L662C11 and couldn't get further.
Sadly my Go abilities are limited - is  configuration via a yaml file no longer supported/encouraged?
