### DISCUSSION TITLE
Reproduction repository for `token signed by untrusted key` (#2875) using dockerized Keycloak

### DISCUSSION THREAD

**Discussion by pankalog** [distribution/distribution#4487] [Q&A]
This discussion is for resolving the issue with **token auth** with the two KIDs (from Distribution and the auth provider) not being in the same format, thus getting the issue `failed to verify token: token signed by untrusted key`. This issue has been going around and I have been asking questions about it in https://github.com/distribution/distribution/issues/2875 . 

I've been able to create a **reproducible environment** in this repository: https://github.com/pankalog/docker-distribution-keycloak 

It's as easy as starting the docker-compose project and running the `docker login` command.

Make sure to **clone the repository** and follow the instructions in the README.

@milosgajdos hope this helps, and I hope other people will find this useful!

Looking forward to your answers!

**Comment by martinrasel** [comment]
Hi,

I've had the same problem for the last few days. I was able to solve it by switching to the Edge version. 

This fix helped me:  https://github.com/distribution/distribution/pull/4471

I also had to set auth.token.jwks in config.yaml. But as soon as I use auth.token.rootcertbundle, I also get the error that it can't find the kid.

I hope it helps you!

**Reply by pankalog** [reply]
> Hi,
> 
> I've had the same problem for the last few days. I was able to solve it by switching to the Edge version.
> 
> This fix helped me: #4471
> 
> I also had to set auth.token.jwks in config.yaml. But as soon as I use auth.token.rootcertbundle, I also get the error that it can't find the kid.
> 
> I hope it helps you!

Hey @martinrasel , thanks for the comment!!

I just pulled the edge version (`ghcr.io/distribution/distribution:edge`), and these are my settings: 

```yaml
auth:
  token:
    realm: https://localhost:8443/realms/test/protocol/docker-v2/auth
    service: docker-registry
    issuer: https://localhost:8443/realms/test
    jwks: /registry/jwks.json
```
So i removed the rootcertbundle and added the jwks. I still get the same error. Are you using Keycloak?

Thanks!

**Reply by martinrasel** [reply]
Hi,

sorry for the confusion... I'm in the process of setting up my servers. I had your error, but than I realized there was something wrong in my conf.yaml. After I fixed the config, the exact same error came back... very frustrating.

But still, I got it working now. 

Regarding your question: yes, I use Keycloak 26, with the docker-v2 extension. It runs in a container that I start with podman-compose.
Outside I have a Nginx running as a reverse proxy.

I know there will be trouble with the developers here, but unfortunately the latest version of registry is not compatible with the current version of docker-v2. Docker-v2 still uses libtrust. So I tried it with version 2.8.3 to see if it works. So please try 2.8.3 - for testing. It is not recommended to use this version.

Otherwise, I stored the RSA certificate of my realm and referenced it in the conf.yaml. I have removed the jws for now.
My conf.yaml looks like this:

```
auth:
  token:
    realm: "https://my.webserver.com/realms/docker-registry/protocol/docker-v2/auth"
    service: "mydocker-v2"
    issuer: "https://my.webserver.com/realms/docker-registry"
    rootcertbundle: /etc/keycloak/keycloak_cert.pem
```
