### DISCUSSION TITLE
Recommendation config s3 for pushing big blobs

### DISCUSSION THREAD

**Discussion by legolego621** [distribution/distribution#4513] [Q&A]
Hello, can you tell me what are the recommended parameters from the s3 configuration side, so that the distribution can serve a large number of clients, and also so that it can effectively push images with a large blob size (more than 7 gigabytes per blob). Considering that s3 is not a bottleneck.

At the moment, I use the following parameters, but it seems that the distribution takes a long time to assemble the blob.

```
    storage:
      s3:
        accesskey: accesskey
        secretkey: secretkey
        secure: true
        v4auth: true
        region: us-west-1
        regionendpoint: https://s3.example.info
        bucket: bucket-name
        chunksize: 5242880
        multipartcopychunksize: 33554432
        multipartcopymaxconcurrency: 100
        multipartcopythresholdsize: 33554432
        rootdirectory: /distribution
        forcepathstyle: true
        accelerate: false
        usedualstack: true
        loglevel: info
```
