### DISCUSSION TITLE
Recommendation to handle imagepullbackoff on Pod

### DISCUSSION THREAD

**Discussion by JuanPatrix** [distribution/distribution#4514] [Q&A]
Hello, i build Docker and push local image to local registry in nodes . When I running runner by k6 to test performance, in total of pods more than 4. I got error on pods `Back-off pulling image "localhost:5000/customk6:0.0.1"`.  

Steps:
```
docker run -dp 5000:5000 --restart=always --name registry registry
docker push localhost:5000/customk6:0.0.1
```

Pods yaml:
```
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: run-k6-with-vars
spec:
  parallelism: 10
  cleanup: post
  script:
    configMap:
      name: crocodile-stress-test
      file: k8test.js
  arguments: -o xk6-influxdb=http://<ip-address>
  runner:
    image: localhost:5000/customk6:0.0.1
    imagePullPolicy: IfNotPresent
    env:
      - name: K6_INFLUXDB_ORGANIZATION
        value: org
      - name: K6_INFLUXDB_TOKEN
        value: token
      - name: K6_INFLUXDB_BUCKET
        value: bucket
```
