### ISSUE TITLE
Crash when starting without an auth handler

### ISSUE THREAD

**Issue by ferrix** [distribution/distribution#1168]
I am running registry:2 (docker image ddfb3bf27ae2) behind an authorizing proxy. Most of my configuration:

```
version: 0.1
log:
  level: warn
  formatter: text
  fields:
    service: registry
    environment: garden
  hooks:
    - type: mail
      levels:
      - panic
      options:
         smtp:
          addr: something
          username: foo
          password: bar
        from: docker@yes.no
    to:
      - people@else.where
storage:
   s3:
http:
  addr: :5000
```

This results in a whine about realm not being set for htpasswd auth. When I enable silly auth with realm and service, I get a nag about path not being set: 

```
auth:
  silly:
    realm: silly-realm
    service: silly-service
```

Then when I set the path, I get a nag that service is not set for silly:

```
auth:
  silly:
    realm: silly-realm
    service: silly-service
    path: '/this/is/not/happening'
```

And finally this works:

```
auth:
  silly:
    realm: silly-realm
    path: '/this/is/not/happening'
    service: silly-service
```

However then I need to send bogus silly `Authorization` headers. The same configuration worked last week.
