### ISSUE TITLE
The registry insists my COMODO issued TLS Cert is signed by an unknown authority

### ISSUE THREAD

**Issue by six0h** [distribution/distribution#1184]
My Docker host is: Docker version 1.9.0, build 76d6bc9
The Daemon I'm using is an equally new docker-machine on OSX.
I have tested this from Ubuntu 14.04 as well as OSX, and while the error message is slightly better on Ubuntu, its complaining about the same thing.

I am trying to run a Docker registry within my network in my data-center. I have run the container with docker-compose as follows:

```
registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/star.hotheadgames.com.crt
    REGISTRY_HTTP_TLS_KEY: /certs/star.hotheadgames.com.key
    REGISTRY_HTTP_TLS_CAS: /certs/star.hotheadgames.com.ca.crt
  volumes:
    - /data/registry/images:/var/lib/registry
    - /data/certs:/certs
```

The registry comes online, seems to accept my certificates just fine, but rejects all pushes into the registry due to 'bad certificate', as you can see below:
Docker Daemon Side:

```
The push refers to a repository [registry.hotheadgames.com:5000/chatops/errbot] (len: 1)
unable to ping registry endpoint https://registry.hotheadgames.com:5000/v0/
v2 ping attempt failed with error: Get https://registry.hotheadgames.com:5000/v2/: x509: certificate signed by unknown authority
 v1 ping attempt failed with error: Get https://registry.hotheadgames.com:5000/v1/_ping: x509: certificate signed by unknown authority
```

Docker Host Side:

```
registry_1 | 2015/11/12 21:34:16 http: TLS handshake error from 172.24.160.62:63967: remote error: bad certificate
```

When i force the client to use --insecure-registry, i can push into it just fine, but I don't want to configure every client to do this, and my certificate IS valid, it's currently present on many of our subdomains, and millions of people around the world are connecting to our clients just fine.

Please assist.
