### ISSUE TITLE
When using /etc/hosts file for DNS go uses its own resolver [solved] 

### ISSUE THREAD

**Issue by egidijus** [distribution/distribution#1362]
I was using distribution with docker compose to deploy portus and registry.

In the docker compose file, I added DNS mappings to the docker host, so registry can post events to portus, and portus can connect to registry via DNS.

But docker registry logs showed that the registry was using a different resolver.

example `docker-compose.yml`

```
portus_web:
  env_file: 
    - prod_portus.env
  image: portus
  command: puma -b tcp://0.0.0.0:3000 -w 3
  volumes:
    - ./portus:/portus
  ports:
    - "3000:3000"
  links:
    - db
  extra_hosts:
    - "docker.business.com:172.17.0.1"
    - "portus.business.com:172.17.0.1"

registry:
  env_file: 
    - prod_portus.env
  image: registry
  links:
    - portus_web
  ports:
    - "5000:5000"
  extra_hosts:
    - "docker.business.com:172.17.0.1"
    - "docker.business.com:172.17.0.1"
```

To ensure that docker registry uses hosts file instead of its own resolver, you must add this variable to docker registry container.

`GODEBUG=netdns=cgo`
