### ISSUE TITLE
PATCH calls fails for registry 2.4.0 when using IAM Instance profile

### ISSUE THREAD

**Issue by mihirv0ra** [distribution/distribution#1684]
I tried searching for this issue and didnt see anyone report it.

We were using the docker registry 2.3.0 and upgraded to 2.4.0 (we use S3 for storage using IAM Instance Profile).
There were no issues with push/pull/delete calls when using 2.3.0.
When we started testing the registry upgrade to 2.4.0 we see that,
The PULL works fine.
When doing push the PATCH calls to the registry fails, with unauthorized errors, 
We haven't tried the delete image operation yet, and would be trying that tomorrow. 
One behavior that was strange was the PUSH for images having just POST calls work as expected, however when images pushed make PATCH calls, the calls fail. 

The configuration we are using is as follows,

```
storage:
    cache:
        blobdescriptor: inmemory
    s3:
        region: us-east-1
        bucket: myregistrybucket
        encrypt: true
        secure: true
        v4auth: true
        chunksize: 5242880
    redirect:
        disable: true
    delete:
        enabled: true
```

Am I missing something ? Is there a mandate to pass the accesskey and secretkey parameters, 

The documentation did say to leave it blank for using instance profile, so do i have to even mention the parameters with "" strings or it should handle with my existing configuration.

Thanks.

**Comment by RichardScothern** [comment]
Does your IAM profile have the necessary permissions?  They changed between 2.3 and 2.4:
https://github.com/docker/distribution/blob/master/docs/storage-drivers/s3.md#s3-permission-scopes

**Comment by timfeirg** [comment]
Mine runs into a very similar issue where push works but pull will fail like yours, and the IAM user has been given full permissions, see in https://github.com/docker/docker/issues/22852#issuecomment-220780910 @RichardScothern

**Comment by timfeirg** [comment]
did you make any progress with this issue? @mv012004

**Comment by RichardScothern** [comment]
@timfeirg : can you post your registry logs?    

What happens when you copy the sample IAM (posted above?)

Also, can you test your setup with the legacy S3 driver? Change the name in the configuration file from `s3` to `s3goamz`.

**Comment by timfeirg** [comment]
@RichardScothern  I changed to `s3goamz`, then push/pull both fail:

```shell
$ docker push localhost:22258/testpush
The push refers to a repository [localhost:22258/testpush]
f6ebe8abdaea: Retrying in 11 seconds
acc5ea83ac4e: Retrying in 11 seconds
85ffd1e01e05: Retrying in 11 seconds
e81197a5814f: Retrying in 11 seconds
481104fae705: Retrying in 11 seconds
1df93d8925b8: Waiting
fd6d078b083f: Waiting
89713c868c2d: Waiting
79a2dc487d51: Waiting
5f70bf18a086: Waiting
be4afcadee58: Waiting
2f12183dca17: Waiting
63538fa1c3d0: Waiting
4300ce4f67ba: Waiting
```

```shell
$ curl http://127.0.0.1:22258/v2/ainur/tags/list
{"errors":[{"code":"UNKNOWN","message":"unknown error","detail":{"DriverName":"s3goamz","Enclosed":{"StatusCode":400,"Code":"InvalidRequest","Message":"The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.","BucketName":"","RequestId":"8C1E1195680452FB","HostId":"USVvdtHh5nklw34cg+OyS3G98sUuCbVyKoeV0VgAraHWh36TmU4zujMxKfO24cEFCx2Lq3ndOzU="}}}]}
```

**Comment by timfeirg** [comment]
are there any working example out there using `s3` as docker registry storage backend?

**Comment by mzupan** [comment]
@timfeirg  this is what I'm using

```
storage:
  s3:
    region: us-east-1
    bucket: company-prod-platform-registry
    secure: true
    v4auth: true
    rootdirectory: /images
  delete:
    enabled: false
  cache:
    blobdescriptor: inmemory
  redirect:
    disable: false
```

**Comment by RichardScothern** [comment]
@timfeirg it looks like your AWS region requires v4 request signing ( `v4auth : true` in the configuration)

**Comment by timfeirg** [comment]
@RichardScothern so now I added the `v4auth : true`, like this:

```yaml
storage:
#  cache:
#    blobdescriptor: redis
#  filesystem:
#    rootdirectory: /mnt/mfs/registry

  maintenance:
    uploadpurging:
      enabled: false
  delete:
    enabled: true
  s3goamz:
    accesskey: xxx
    secretkey: xxxx
    regionendpoint: http://s3.cn-north-1.amazonaws.com.cn
    region: cn-north-1
    bucket: xxx
    v4auth : true
```

now push works but pull says `error pulling image configuration: unauthorized: authentication required`
