### ISSUE TITLE
Registry S3 driver failed to upload images to Swift3 (S3 compatible API entry) with both v2 and v4 signature

### ISSUE THREAD

**Issue by HugoKuo** [distribution/distribution#2326]
In my testing with registry 2, 2.6, 2.6.1. The s3 drvier doesn't work properly with OpenStack Swift's S3 API. 

With v2, the push image always got http: no Host in request URL error. 

```
root@ubuntu1404-base:~# docker push localhost:5000/bbox
The push refers to a repository [localhost:5000/bbox]
3a1dff9afffd: Pushing [==================================================>]  1.309MB
http: no Host in request URL
```

For S3 v4 signature, the Invalid path: `http%3A//192.168.1.42%3A80/docker-s3/docker/reg` one comes from the aws-go-sdk that we discovered and reported to aws-go-sdk before. It was fixed in aws-go-sdk 1.5+. I pulled the latest docker registry and it's using go sdk 1.2.4 which has this issue. The AWS S3 can handle the encoded path but not Swift's Swift3 API. https://github.com/aws/aws-sdk-go/issues/944

v2 signature registry instance configuration as below. 

```
root@ubuntu1404-base:~# cat registry-container/local-aws-config.yml
version: 0.1
log:
  level: debug
  accesslog:
    disabled: false
fields:
  service: registry
storage:
  cache:
    blobdescriptor: inmemory
  s3:
    accesskey: docker
    secretkey: 847093a6840a944244c69eedcf379e4a
    region: US
    regionendpoint: http://rrdns.openstack.com.tw
    bucket: docker-s3
    encrypt: false
    #keyid:
    secure: false
    v4auth: false
    chunksize: 5242880
    multipartcopychunksize: 33554432
    multipartcopymaxconcurrency: 100
    multipartcopythresholdsize: 33554432
    rootdirectory: /
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```

v4 signature registry instance configuration as below : 

```
version: 0.1
log:
  level: debug
  accesslog:
    disabled: false
fields:
  service: registry
storage:
  cache:
    blobdescriptor: inmemory
  s3:
    accesskey: docker
    secretkey: 847093a6840a944244c69eedcf379e4a
    region: us-east-1
    regionendpoint: rrdns.openstack.com.tw
    bucket: docker-s3
    encrypt: false
    #keyid:
    secure: false
    v4auth: true
    chunksize: 5242880
    multipartcopychunksize: 33554432
    multipartcopymaxconcurrency: 100
    multipartcopythresholdsize: 33554432
    rootdirectory: /
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```
