### ISSUE TITLE
Proposal to Support Proxy Protocol

### ISSUE THREAD

**Issue by nathanjsweet** [distribution/distribution#2404]
The current version of the docker registry is able to terminate SSL by itself. It is not unreasonable to load balance the current docker registry with a TCP load balancer, especially given that access logging is also possible. The current version of the docker registry should enable support for accepting the commonly used "proxy-protocol" TCP header. Enabling this would allow future changes to access logs to include real client ip addresses.

Here is a sample configuration possibility:

```yml
http:
  addr: localhost:5000
  net: tcp
  proxyprotocol: true
  debug:
    addr: localhost:5001
    proxyprotocol: false
```

I propose having two flags, one for the main listener, and one for the debug listener. The debug listener needs its own configuration for proxy-protocol as well, as appliances, like ELBs (in AWS), don't utilize proxy protocol when making health checks.

The proxy protocol is fairly lightweight to wrap, so I propose submitting a pull request not based on any existing library. I'm happy to do the work, but I am open to someone else doing it as well (if they want).
