### ISSUE TITLE
GET /v2/_catalog causes "oss: invalid path: /docker/registry/v2/repositories/" when using oss storage driver

### ISSUE THREAD

**Issue by kaoet** [distribution/distribution#2410]
Config: 
```yaml
storage:
  oss:
    accesskeyid: <hidden>
    accesskeysecret: <hidden>
    region: oss-cn-qingdao
    secure: false
    bucket: <hidden>
```

Then `curl https://my-registry/v2/_catalog`.

Error log:
```
2017/09/22 05:39:07 GET http://<hidden>.oss-cn-qingdao.aliyuncs.com/?delimiter=%2F&marker=&max-keys=1000&prefix=docker%2Fregistry%2Fv2%2Frepositories%2F ...
time="2017-09-22T05:39:08Z" level=error msg="response completed with error" err.code=unknown err.detail="oss: invalid path: /docker/registry/v2/repositories/" err.message="unknown error" go.version=go1.7.6 http.request.host=<hidden> http.request.id=78fdbfa8-5653-4be6-ac8a-2e7c942fd236 
```

Possible fix: #2409
