### ISSUE TITLE
Proposal to make middleware hooks pluggable

### ISSUE THREAD

**Issue by nathanjsweet** [distribution/distribution#2417]
With go1.8 it is possible to dynamically link go programs into another go program using [the plugin package](https://golang.org/pkg/plugin/). I propose using this package and modifying the Middleware configuration interface slightly to allow people to load dynamic modules into the registry that conform to the 3 different Middleware interfaces.

This will make it a lot easier for people to implement these plugins without having to fork the main repository and will help organizations contribute to and use the mainline project without open sourcing what might be proprietary/sensitive code (my own company's use case).

Proposed Configuration Change:
```yml
middleware:
  registry:
    - name: ARegistryMiddleware
    - type: plugin # default is build, which is the current method
    - path: /path/to/registry/plugin.so
    - checksum: 987eransdf72uoifjsadfsae0928rsfklj
      options:
        foo: bar
```

~~I propose that these plugins be loaded in within the `NewRegistry` method~~ I propose that these plugins be loaded within the `NewRegistry` method and initialized in `NewApp`, and that and optional hash configuration option be added to the middleware configuration section so that the shared object can be content-verified. The loading process would do content verification and make sure that the plugin conforms to the interface type, and will then finally "register" it.

I will be doing this work for my own company regardless of whether this gets mainlined, so if you guys are interested *please* get back to me with your suggestions or comments as soon as you can so I can adjust accordingly.
