### ISSUE TITLE
docker push keep retrying and fail with "http: no Host in request URL" when using ceph s3 as backend storage

### ISSUE THREAD

**Issue by fffffreedom** [distribution/distribution#2517]
hi guys

 i'm trying to use ceph s3 as docker registry's backend storage.  when pushing image onto registry, 
it keep retrying:  
```
# docker push 10.101.17.83:5000/ceph:2
The push refers to a repository [10.101.17.83:5000/ceph]
d16d06b02271: Pushing [==================================================>] 23.54 MB
0912b310db10: Retrying in 4 seconds 
6767cac03a2d: Retrying in 5 seconds 
...
http: no Host in request URL
```
following is my config:   
```

version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  s3:
    accesskey: N396449FK5IVBKD46D2Y
    secretkey: <redacted>
    region: default
    regionendpoint: http://storage.work.com
    bucket: registry
    secure: false
    v4auth: false
    chunksize: 5242880
    rootdirectory: /registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```
and i'm using ceph jewel 10.2.10 verion

thanks
