### ISSUE TITLE
storage use oss has a error "failed to garbage collect: failed to mark: oss: invalid path: /docker/registry/v2/repositories/" when GC

### ISSUE THREAD

**Issue by russellgao** [distribution/distribution#2595]
harbor:v1.3.0
registry:vmware/registry:2.6.2-photon
docker : Docker version 1.12.6, build 78d1802 
docker-compose: docker-compose version 1.14.0-rc2, build 24dae73

/etc/registry/config.yml
```
storage:
    cache:
        layerinfo: inmemory
#    filesystem:
#        rootdirectory: /storage
    oss:
        accesskeyid: ********
        accesskeysecret: ********
        region: oss-cn-hangzhou
#        endpoint: oss-cn-hangzhou-internal.aliyuncs.com
        internal: true
        bucket: ********
        encrypt: false
        secure: true
        chunksize: 5242880
        rootdirectory: harbor-qf
    maintenance:
        uploadpurging:
            enabled: true
            age: 168h
            interval: 24h
            dryrun: false
    delete:
        enabled: true
```
run command : 
```
docker run -it --name gc --rm --volumes-from registry vmware/registry:2.6.2-photon garbage-collect --dry-run /etc/registry/config.yml
```
error log : 
```
failed to garbage collect: failed to mark: oss: invalid path: /docker/registry/v2/repositories/
```
Any ideas on how to fix it?
