### ISSUE TITLE
The cache is deleted by docker registry at mirror proxy mode

### ISSUE THREAD

**Issue by mlb-1** [distribution/distribution#2736]
The cache is deleted when i set `maintenance.uploadpurging.enabled=false`.  Why? And How do you keep the cache valid for a very long time?

config.yml:
```
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  maintenance:
    uploadpurging:
      enabled: false
http:
  addr: :30000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
proxy:
  remoteurl: http://192.168.23.94:8092
  username: admin
  password: xxxxxx
```
