### ISSUE TITLE
Private Registry "invalid authorization credential" appears, but everything works fine.

### ISSUE THREAD

**Issue by GEownt** [distribution/distribution#2817]
We use a Private Docker Registry and everything works fine, but we get this error message everytime we **push** a image into the Registry:
```
time="2019-01-15T05:50:24.629888749Z" level=warning msg="error authorizing context: basic authentication challenge for realm "My Docker Registry Realm": invalid authorization credential" go.version=go1.11.2 http.request.host="my-registry.my.domain:443" http.request.id=e57cef36-9230-4b8a-8ad8-b2c2a1860a6f http.request.method=GET http.request.remoteaddr="XXX.XXX.XXX.XXX:42626" http.request.uri="/v2/" http.request.useragent="docker/18.09.0 go/go1.10.4 git-commit/4d60db4 kernel/3.10.0-957.1.3.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.0 \(linux\))" 
```

This is how we configure our Registry:
```
version: "2"
services:
  registry:
    image: registry:latest
    restart: always
    ports:
      - 443:5000
    volumes:
      - ./certs:/certs
      - ./auth:/auth
      - ./data:/var/lib/registry
    environment:
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=My Docker Registry Realm
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/my-registry.my.domain.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/my-registry.my.domain.key
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_LOG_LEVEL=warn
      - REGISTRY_HTTP_HOST=https://my-registry.my.domain:443
```

We tried it with different Docker Versions but everytime we get this error message. We are not using a proxy between the Client and Server
