### ISSUE TITLE
Support redis sentinel cluster

### ISSUE THREAD

**Issue by jeremyxu2010** [distribution/distribution#2885]
I use external [redis sentinel cluster](https://redis.io/topics/sentinel) to ensure the HA of redis. But docker registry DOES NOT support redis sentinel cluster.

I want configure redis sentinel cluster like this:

```yaml
redis:
  addr: xxx.xxx.xxx.xx:26379,xxx.xxx.xxx.xx:26379,xxx.xxx.xxx.xx:26379
  sentinelMasterSet: mymaster
  password: asecret
  db: 0
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s
```

BTW, redis sentinel cluster can be deployed on the kubernetes usng helm chart [redis-ha](https://github.com/helm/charts/tree/master/stable/redis-ha) easily.
