### ISSUE TITLE
Prometheus /metrics not working on the last build image!

### ISSUE THREAD

**Issue by ernestoalejandrocu** [distribution/distribution#2935]
Hello guys, today i make one git clone from repo using master, and compile the image, i try to test
```yaml
http:
  addr: ":5000"
  debug:
    addr: ":5001"
    prometheus:
      enabled: true
      path: "/metrics"
```
but the prometheus section, those lines, apears like unreconized variables on docker registry. Any body can help here.

I make curl -v localhost:5001/debug/vars and i receive data, thats is ok, but i need take that data to my grafana dashboard,  any experience on this.

**Comment by ptman** [comment]
This works for me:

```yaml
http:
  addr: ':5000'
  debug:
    addr: ':5001'
    prometheus:
      enabled: true
      path: '/metrics'
  headers:
    X-Content-Type-Options: [nosniff]
```

`curl http://registry:5001/metrics` and prometheus can get the values too
