### ISSUE TITLE
{"errors":[{"code":"UNSUPPORTED","message":"The operation is unsupported."}]} in delete API

### ISSUE THREAD

**Issue by ricardolimaui** [distribution/distribution#2959]
Hello all
Currently I have a docker-compose with these config
```
version: '3'
services:
  docker_hub:
    image: registry:2.7.1
    container_name: docker_hub
    ports:
      - 5001:443
      #- 5000:5000
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED = true
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry 
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/public.crt 
      - REGISTRY_HTTP_TLS_KEY=/certs/private.key 
      - REGISTRY_HTTP_ADDR=0.0.0.0:443
      - SEARCH_BACKEND= sqlalchemy
    volumes:
      - DATA_CERT_HUB:/certs
      - DATA_HUB_REGISTRY:/var/lib/registry
      - DATA_AUTH_HUB:/auth


volumes:
  DATA_AUTH_HUB:
  DATA_CERT_HUB:
  DATA_HUB_REGISTRY:
```

But know when I try to delete some image with 
`curl -X DELETE -u user:pass -v https://url/v2/app/manifests/0.1 -H 'Accept: application/vnd.docker.distribution.manifest.v2+json'`
The 0.1 it was also replaced with digest but the result is the same 

Then the respond comes with 
{"errors":[{"code":"UNSUPPORTED","message":"The operation is unsupported."}]}

What is wrong ? It is because of because protected with tls ? I am not also able to get a web ui.. it needs more config in docker-compose ?

Thank you
