### ISSUE TITLE
swift failed to garbage collect

### ISSUE THREAD

**Issue by liuxu623** [distribution/distribution#3016]
```
registry garbage-collect -d /etc/registry/config.yml

DEBU[0325] swift.Walk("/docker/registry/v2/blobs")       go.version=go1.11.8 instance.id=aebb6994-18d2-438a-a548-4d2b1c864d26 service=registry trace.duration=42.285913041s trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Walk" trace.id=fdf9ffb0-90e4-4dee-bda7-3b18bc3d3bcd trace.line=232
failed to garbage collect: error enumerating blobs: swift: Timeout expired while waiting for segments of /docker/registry/v2/blobs/sha256/0e/0e13df4de72ab99c36328542e7a42eef9f1b3b3b61ca0a063ec5de2c3a3923c1/data to show up
```
```
swift list --lh registry -p files/docker/registry/v2/blobs/sha256/0e/0e13df4de72ab99c36328542e7a42eef9f1b3b3b61ca0a063ec5de2c3a3923c1/
   0 2019-09-26 13:03:02 application/octet-stream files/docker/registry/v2/blobs/sha256/0e/0e13df4de72ab99c36328542e7a42eef9f1b3b3b61ca0a063ec5de2c3a3923c1/data
   0
```
same as #2188

**Comment by shcherbak** [comment]
https://github.com/distribution/distribution/issues/2188#issuecomment-1000315090

**Comment by shcherbak** [comment]
have the same issue. Registry is consistent, Confusing that error message ``segments of /docker/registry/v2/``` has no prefix ```files/docker/registry/v2/``` ```files```

**Comment by shcherbak** [comment]
the same issue with 2.8.0 release

**Comment by shcherbak** [comment]
We are still suffering of this problem. If you need any details, please refer, i will provide information you need to fix this.
We have intensively used registry setup with swift backend and unable to clean it properly

**Comment by shcherbak** [comment]
We have large and intensively used registry, for example there is repositories with more then 500 tags. We investigated that garbage collect hangs when need to remove many (apx more then 1000 blobs). When we did garbage collecting with custom script, native garbage collect starts working fine

**Comment by devlifealways** [comment]
I'm writing this for those still struggling with this issue, I had the same problem but did things differently. Given that OVH's swift expose an S3 compatible API, I did change registry's driver to S3 instead of Swift to be able to run **[docker-distribution-pruner](https://gitlab.com/gitlab-org/docker-distribution-pruner)** which is far quicker and enhanced than vanilla `registry garbage-collect -m` command.

To wrap up things a little bit, here are the steps to follow to cut half time the GC process : 
1. change driver to s3 
   ```yaml
        storage:
          s3:
            rootdirectory: files # swift uses this prefix, could be something else, check your configuration
            region: XXXX 
            bucket: XXXXXXXXXXXXXXXX
            accesskey: XXXXXXXXXXXXXXXXXXXXXX
            secretkey: XXXXXXXXXXXXXXXXXXXXXX
            regionendpoint: XXXXXXXXXXXXXXXXXXXXXXXX 
            v4auth: true
   ```
2. run docker **docker-distribution-pruner** binary
   ```shell
    # say your registry configuration file is at /tmp/config_s3.yml
     $ EXPERIMENTAL=true docker-distribution-pruner \
        -config=/tmp/config_s3.yml \
        -parallel-repository-walk \
        -parallel-blob-walk \
        -soft-errors \ # there is an issue with Swift's DLOs, probably you'll find few empty segments that could stop the process
        -delete \
        --repository-csv-output registry_gc.csv 
   ```

Hope it helps,
