### ISSUE TITLE
Registry crash with s3 driver

### ISSUE THREAD

**Issue by Toub** [distribution/distribution#3180]
I am using 2 registries hosted as docker containers:
- 1 private registry
- 1 proxy registry

Both are crashing (and restarting) multiple times a day.

Here is the last error stack from private registry:

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc4e6bd]

goroutine 8 [running]:
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).doWalk.func1(0xc000130080, 0xc0028c4f01, 0xc002898998)
	/go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:973 +0x9d
github.com/docker/distribution/vendor/github.com/aws/aws-sdk-go/service/s3.(*S3).ListObjectsV2PagesWithContext(0xc0003d01c0, 0x7faec9607dc0, 0xc000af2070, 0xc003c400a0, 0xc0001aba98, 0x0, 0x0, 0x0, 0x1, 0x2)
	/go/src/github.com/docker/distribution/vendor/github.com/aws/aws-sdk-go/service/s3/api.go:4198 +0x111
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).doWalk(0xc0003cd200, 0xff1ae0, 0xc000af2000, 0xc002898b58, 0xc000170141, 0x31, 0x0, 0x0, 0xc000e9c8a0, 0x0, ...)
	/go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:971 +0x3a1
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).Walk(0xc0003cd200, 0xff1ae0, 0xc000af2000, 0xc000388e40, 0x20, 0xc000e9c8a0, 0x2, 0x0)
	/go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:919 +0x160
github.com/docker/distribution/registry/storage/driver/base.(*Base).Walk(0xc000120c90, 0xff1ae0, 0xc000af2000, 0xc000388e40, 0x20, 0xc000e9c8a0, 0x0, 0x0)
	/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go:239 +0x234
github.com/docker/distribution/registry/storage.getOutstandingUploads(0xff1c20, 0xc000397b80, 0xffd980, 0xc000120c90, 0x2, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/distribution/registry/storage/purgeuploads.go:70 +0x236
github.com/docker/distribution/registry/storage.PurgeUploads(0xff1c20, 0xc000397b80, 0xffd980, 0xc000120c90, 0xbf7def06ded31a63, 0xfffddb1567344d45, 0x17297c0, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/docker/distribution/registry/storage/purgeuploads.go:34 +0x163
github.com/docker/distribution/registry/handlers.startUploadPurger.func1(0x10015c0, 0xc000158730, 0xff1c20, 0xc000397b80, 0xffd980, 0xc000120c90, 0x2260ff9290000, 0x0, 0x4e94914f0000)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:1071 +0x221
created by github.com/docker/distribution/registry/handlers.startUploadPurger
	/go/src/github.com/docker/distribution/registry/handlers/app.go:1064 +0x2e9
```

On client side (CI), I have the following error during an upload (not 100% sure if it is at the exact same time): 

```bash
2c719774c1e1: Mounted from my-app/my-app-fullstack/my-app-dev-base
3f2efe9dceb1: Pushed
ec62f19bb3aa: Mounted from my-app/my-app-fullstack/my-app-dev-base
f94641f1fe1f: Mounted from my-app/my-app-fullstack/my-app-dev-base
8f19d9738a31: Retrying in 5 seconds
8f19d9738a31: Retrying in 4 seconds
8f19d9738a31: Retrying in 3 seconds
8f19d9738a31: Retrying in 2 seconds
8f19d9738a31: Retrying in 1 second
error parsing HTTP 404 response body: invalid character 'p' after top-level value: "404 page not found\n"
The push refers to repository [private.registry.my-domain.com/my-app/my-app-fullstack/my-app-server-api]
5f70bf18a086: Preparing
8f19d9738a31: Preparing
...
330936718dad: Waiting
62674da13057: Waiting
error parsing HTTP 404 response body: invalid character 'p' after top-level value: "404 page not found\n"
```

Here is the private registry config:

```yml
# https://docs.docker.com/registry/configuration
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  s3: # https://docs.docker.com/registry/storage-drivers/s3/
    rootdirectory: /private-registry
    region: digitalocean-xxxx
    regionendpoint: xxxx.digitaloceanspaces.com
    bucket: xxxxxxxxxxxx-registry
    accesskey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    secretkey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  delete:
    enabled: true
#   maintenance:
#     uploadpurging:
#       enabled: true
#       age: 168h
#       interval: 24h
#       dryrun: false
http:
  addr: :5000
  secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
log:
  accesslog:
    disabled: true
  level: warn
  formatter: text
```

And the proxy one:

```yml
# https://docs.docker.com/registry/configuration
version: 0.1
log:
  fields:
    service: registry
proxy: # https://docs.docker.com/registry/recipes/mirror/
  remoteurl: https://registry-1.docker.io 
storage:
  cache:
    blobdescriptor: inmemory
  s3: # https://docs.docker.com/registry/storage-drivers/s3/
    rootdirectory: /proxy-registry
    region: digitalocean-xxxx
    regionendpoint: xxxx.digitaloceanspaces.com
    bucket: xxxxxxxxxxxx-registry
    accesskey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    secretkey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  delete:
    enabled: true
#   maintenance:
#     uploadpurging:
#       enabled: true
#       age: 168h
#       interval: 24h
#       dryrun: false
http:
  addr: :5000
  secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
log:
  accesslog:
    disabled: true
  level: warn
  formatter: text
```
