### ISSUE TITLE
multi proxy support

### ISSUE THREAD

**Issue by fanux** [distribution/distribution#3253]
```
proxy:
  remoteurl: https://registry-1.docker.io
  username: [username]
  password: [password]
```

```
proxy:
- remoteurl: https://registry-1.docker.io
  username: [username]
  password: [password]
- remoteurl: https://hub.docker.io
  username: [username]
  password: [password]
```
