### ISSUE TITLE
panic: StorageDriver not registered: oss

### ISSUE THREAD

**Issue by jianwang-beijing** [distribution/distribution#3389]
I got the storage driver error when use the OSS. The reproduce step:

1. git clone latest code
2. run `make` command to build the registry
3. start the registry server: `./registry serve ./config.yml`

the config.yml looks:
```
version: 0.1
log:
  fields:
    service: registry
loglevel: debug # deprecated: use "log"
storage:
  oss:
    accesskeyid: xxx
    accesskeysecret: xxx
    region: oss-cn-hangzhou
    endpoint: research-ng-main.oss-cn-hangzhou.aliyuncs.com
    bucket: research-ng-main
    encrypt: true
    rootdirectory: crstorage
  cache:
    blobdescriptor: inmemory
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```

I have checked the source code and I find that the `registry/storage/driver/factory/factory.go`  `Register` function is not be called in OSS driver. It is maybe the error reason. Please check the problem. If I use the OSS withe error way, please also reply me what is the right way to use.
