### ISSUE TITLE
Periodic stuck pulls require restarts to fix until they start to happen again

### ISSUE THREAD

**Issue by dg424** [distribution/distribution#3390]
Hi,

We've deployed a caching registry using version 2.7.1. The problem we're having is that pulls periodically hangs (they get stuck on a random layer and do not move forward) and the only way to fix, temporarily, is to restart the registry cache. How can we troubleshoot this or what other information can we provide to help find the issue here ?

Thanks

**Comment by deleteriousEffect** [comment]
@dg424 could you please provide logs from the registry from around the time of the hangs?

What kind of cache are you using?

**Comment by dg424** [comment]
Hi,
This is a docker container image registry. This is our current configuration:

`/ # cat /etc/docker/registry/config.yml
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
`

We do not have logging enabled as per here - https://docs.docker.com/registry/configuration/#log. We've been restarting the registry as the problem happens to get things back online, so I think we might have lost the docker logs. Is there anything we can set in the configuration to prepare for the next time this happens ? Is there any known issue with pulls (or pushes) getting stuck after a period of time with the only recourse being to restart to fix ?

Thanks

**Comment by deleteriousEffect** [comment]
> We do not have logging enabled as per here

I believe you can only disable the access log, regular logging should still be active and that should be enough

> We've been restarting the registry as the problem happens to get things back online, so I think we might have lost the docker logs. Is there anything we can set in the configuration to prepare for the next time this happens ?

I think so, if you encounter this issue again, please capture the logs before restarting

> Is there any known issue with pulls (or pushes) getting stuck after a period of time with the only recourse being to restart to fix ?

Not to my knowledge. Are you using a plain local filesystem, or something like an NFS share or iSCSI that communicates over a network?

**Comment by sizowie** [comment]
Same issues with 3.0 and 3.1 with local filesystem as storage - but using it exclusivly as proxy. Will check the logs when it happens again - but last time there wasn't any noticable special.

```
version: 0.1
log:
  level: info
  fields:
    service: registry

storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 10
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: false
  tag:
    concurrencylimit: 8
  delete:
    enabled: true

http:
  addr: :5000
  tls:
    clientcas:
      - /etc/ssl/certs/ca.pem
  headers:
    X-Content-Type-Options: [nosniff]
  client:
    timeout: 600s
  http2:
    disabled: false
  h2c:
    enabled: false

proxy:
  remoteurl: ...
  ttl: 720h
```
