### ISSUE TITLE
`docker-compose up --no-build` complains that build path does not exist

### ISSUE THREAD

**Issue by macdjord** [distribution/distribution#3405]
# How to reproduce
* Create a `docker-compose.yml` file as such:
  ```yaml
  version: "2.4"

  services:
    foo:
      image: "registry.gitlab.com/REDACTED/foo:latest"
      build: "./foo/"
  ```
* Get the necessary image: `docker pull 'registry.gitlab.com/REDACTED/foo:latest'`
* Do not create the `foo/` directory
* Invoke Docker-Compose like so: `docker-compose up --no-build`

# Expected result
* Container 'foo' should be created using the existing 'foo:latest' image
* Docker-Compose should not care about the presence or absence of the build directory, since it has been explicitly ordered *not* to build anything

# Actual result
```text
ERROR: build path /home/[REDACTED]/foo either does not exist, is not accessible, or is not a valid URL.
```
