### ISSUE TITLE
error with rook object store as s3 backend

### ISSUE THREAD

**Issue by rmanibus** [distribution/distribution#3412]
I am trying to run a registry with a s3 like backend (rook object storage). Every requests to the storage backend are failing with error code 400.

And I'm getting the following error in the registry logs: 
```
{"auth_user_name":"Loic.hermann","code":"UNKNOWN","correlation_id":"66e3e0a8eaf11777e73a1bbb98774070","detail":"s3aws: AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-central-1'\n\tstatus code: 400, request id: 4G1G8H9XCFQVEYM9, host id: 5ykHQ5yNOQBl9mOz+L2DP9IGTXdw4RaPEzjQ09hqZ+6zzOiHGMbsky5qZDJ+zPu4peh1pZYVjuw=","error":"unknown: unknown error","go_version":"go1.16.3","level":"error","msg":"unknown error","root_repo":"sciam","time":"2021-05-06T15:52:32Z","vars_name":"sciam/projects/sciam.fr","vars_reference":"latest"}
{"content_type":"application/json","correlation_id":"66e3e0a8eaf11777e73a1bbb98774070","duration_ms":156,"host":"registry.sciam.fr","level":"info","method":"GET","msg":"access","proto":"HTTP/1.1","referrer":"","remote_addr":"192.168.59.175:52166","remote_ip":"92.184.124.53","status":500,"system":"http","time":"2021-05-06T15:52:32Z","ttfb_ms":156,"uri":"/v2/sciam/projects/sciam.fr/manifests/latest","user_agent":"docker/20.10.6 go/go1.13.15 git-commit/8728dd2 kernel/5.11.0-16-generic os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.6 \\(linux\\))","written_bytes":123}
```

Rados Gtw Logs (I'm not sure it's related but seems corelated):
```
debug 2021-05-06T16:01:33.677+0000 7f3579ce6700  0 WARNING: RGWRados::log_usage(): user name empty (bucket=), skipping
```

my registry config:

```
storage:
  s3:
    host: rook-ceph-rgw-ceph-object-store.ceph-system.svc
    regiondendpoint: http://rook-ceph-rgw-ceph-object-store.ceph-system.svc:80
    path_style: true
    region: us-east-1
    bucket: gitlab-registry-storage
    accesskey: NP9F4FWJJ20BKY7KD0D9
    secretkey: [redacted]
    secure: false
    v4auth: true
  redirect:
    disable: true
```

Am I doing something wrong ?

Thanks a lot !
