### ISSUE TITLE
Docker 3.3.1+ not compatible with SAMBA

### ISSUE THREAD

**Issue by doyelese** [distribution/distribution#3413]
We have a Samba server that we are using for remote files on our development docker environment.

```yml
volumes:
  samba-storage:
    driver: local
    driver_opts:
      type: "cifs"
      device: "//${SAMBA_IP}/storage/"
      o: "username=${SAMBA_USER},password=${SAMBA_PASS},file_mode=0777,dir_mode=0777"
```

Ever since Docker 3.3.1+ any files that are retrieved from this server via apache get polluted with random headers and footers that cause images to fail loading. Example files are attached.

Test1.txt is a plain file with only the contents `Test, pls no question marks`

when retrieved from the server it is downloaded as attached with random stuff added. 

[test1.txt](https://github.com/distribution/distribution/files/6443372/test1.txt)

This is very problematic for our development experience and as such we've had to rollback to 3.2.2.

Any ideas of what Docker can do to fix this?
