### ISSUE TITLE
Docker Registry Empty unless accessed via localhost

### ISSUE THREAD

**Issue by cawoodm** [distribution/distribution#3443]
When I query my local registry with `curl http://localhost:5000/v2/_catalog` I get a list of images ("repositories"). When I query the same host from a different machine with curl `` http://myhost.mydomain.com:5000/v2/_catalog` I get nothing `{}`.

When I shell into the registry container I can see the repositories in `/var/lib/registry/docker/registry/v2/repositories`.

Somehow the registry is using the `Host` header as a key to the name of the repository I guess? I don't wan this - any hostname which reaches this host and port should work the same.

### Other Info
* `docker run -d -p 5000:5000 --restart=always --name registry registry:2`
* `Image registry:2`
* `sha256:1fd8e1b0bb7ef6cc63e0094e2fb5a35259bdce7041ef5e7e4c99694ded1041d7`

### /etc/docker/registry/config.yml
```
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```
