### ISSUE TITLE
Feature：add trace features 

### ISSUE THREAD

**Issue by lengrongfu** [distribution/distribution#3451]
I hope to observe my mirror distribution process through opentracing, so I hope to add the Trace function. Do you have this requirement? Can you introduce it?

**Comment by milosgajdos** [comment]
This isnt on the roadmap at the moment but could be discussed if there is enough interest or even a PR that can kick off the conversation.

**Comment by lengrongfu** [comment]
@milosgajdos Do you mean to submit a PR first, and then discuss based on the PR?

**Comment by lengrongfu** [comment]
@milosgajdos I hope you can take the time to reply to this question, thanks.

**Comment by lengrongfu** [comment]
issue： https://github.com/distribution/distribution/issues/3475

**Comment by lengrongfu** [comment]
Test Env:
    Mac 
    Docker: 20.10.7

Otel: 
   docker-compose up -d 
 ```yml
version: "2"
services:

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Collector
  otel-collector:
    image: ${OTELCOL_IMG}
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "53989:4317"        # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
```
distribution:
```shell
  // config
    otel:
      exporter_name: otlp
      exporter_endpoint: demo_otel-collector_1:4317
 // run command
     $ docker run -p 5000:5000 -d --name registry registry
     $ docker network connect demo_default registry
```
  
Effect：

![image](https://user-images.githubusercontent.com/15009201/128964348-d67dc640-06e5-4ecf-ac1a-f4bb6c667b0f.png)
