### ISSUE TITLE
Feature: add an extra endpoint for s3 storage backend

### ISSUE THREAD

**Issue by bitsf** [distribution/distribution#3493]
When we setup an internal s3 compatible storage backend and want to enable redirect for blobs pulling, registry distribution will use only one endpoint for pulling and pushing, that would make network for pushing. I hope to add a extra endpoint to separate the operation.
The setting can be added in config.yml
```
storage:
  s3:
     regionendpoint: https://192.168.0.100
     redirectendpoint: https://minio.harbor.xxx.com
```

or add in `redirect` section
```
storage:
  redirect:
     disable: false
     endpoint: https://minio.harbor.xxx.com
  s3:
     regionendpoint: https://192.168.0.100
```
