### ISSUE TITLE
azure registry storage driver: unknown blob

### ISSUE THREAD

**Issue by bad2cat** [distribution/distribution#3574]
when i use azure blob as image storage, i found a question that is push image with error: unknown blob

log records 
"HEAD /v2/test/alphtine/blobs/sha256:5843afab387455b37944e709ee8c78d7520df80f8d01cf7f861aae63beeddb6b HTTP/1.1" 307 0 "" "docker/20.10.2 go/go1.13.15 git-commit/8891c58 kernel/5.11.0-43-generic os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.2 \\(linux\\))"

but when i changed to filesystem or oss as image storage,the push is fine

docker registry version: v2.7.0

**Comment by milosgajdos** [comment]
Can you please try to build from `main` branch and see if the issue persists? Note that `2.7.x` branches have not been updated for a while, and the latest pre-release doesn't ship any updates to `Azure` storage driver either.

If you don't want to build the binary manually, you can pull the image from Docker Hub (the `main` branch builds are pushed to `edge` tag; see [here](https://hub.docker.com/repository/docker/distribution/distribution/tags?page=1&ordering=last_updated))

**Comment by bad2cat** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by bad2cat** [comment]
@milosgajdos i use main branch push my image, still has this problem

**Comment by milosgajdos** [comment]
Unfortunately, I've no expertise in Azure services, so won't be of much help I'm afraid. Maybe someone from the wider community will help.

**Comment by sajayantony** [comment]
@shizhmsft or @aviral26

**Comment by shizhMSFT** [comment]
@bad2cat Could you provide more details on the setup? I am not able to reproduce it with the registry built from the `main` branch (8925814ba1ab858243d712db488d45d3d40dfc0b).

Details can be

- Registry config file (with credentials omitted).
- How the registry binary was built.
- What the client version is, and what commands are executed at the client side.

**Comment by shizhMSFT** [comment]
Besides, could you also have a try on a new Azure Blob Storage container? Data inconsistency can also lead to this issue.

**Comment by bad2cat** [comment]
@shizhMSFT 

i look through Docker Registry documentation，have found a configuration

[Docker Registry Configuration](https://docs.docker.com/registry/configuration/#redirect)

when i changed it's value is true, everything is worked

there is my storage configuration：
storage:
      azure:
        accountname: ***
        container: ***
        realm: core.chinacloudapi.cn
      redirect:
        disable: true

Does it's means azure blob can't route all data from registry，only support redirecting to the backend?

**Comment by shizhMSFT** [comment]
@bad2cat I've tested with both `redirect` set to `true` and `false`. Both settings works for me.

Output:
```
➜  ~ curl "http://localhost:5000/v2/alpine/blobs/sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3" -I
HTTP/1.1 307 Temporary Redirect
Content-Type: application/octet-stream
Docker-Distribution-Api-Version: registry/2.0
Location: https://<account_name>.blob.core.windows.net/distribution//docker/registry/v2/blobs/sha256/59/59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3/data?se=2022-01-26T07%3A25%3A22Z&sig=<sas_sig>%3D&sp=r&sr=b&sv=2018-03-28
X-Content-Type-Options: nosniff
Date: Wed, 26 Jan 2022 07:05:22 GMT

➜  ~ curl "http://localhost:5000/v2/alpine/blobs/sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3" -I
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: max-age=31536000
Content-Length: 2818413
Content-Type: application/octet-stream
Docker-Content-Digest: sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3
Docker-Distribution-Api-Version: registry/2.0
Etag: "sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3"
X-Content-Type-Options: nosniff
Date: Wed, 26 Jan 2022 07:05:59 GMT
```

**Comment by shizhMSFT** [comment]
@bad2cat Could you provide the full configuration file with sensitive data removed? Thus we can help you if there is an configuration error.

**Comment by bad2cat** [comment]
@shizhMSFT

ok，my registry deploy on k8s，use image is docker pull distribution/distribution:edge

there is my configuration:

`apiVersion: v1
data:
  config.yml: |
    version: 0.1
    log:
      level: info
      fields:
        service: registry
    storage:
      azure:
        accountname: ***
        container: ***
        realm: core.chinacloudapi.cn
      cache:
        layerinfo: redis
      maintenance:
        uploadpurging:
          enabled: false
      delete:
        enabled: true
      redirect:
        disable: false
    redis:
      addr: localhost:6379
      db: 13
      password: ******
      readtimeout: 10s
      writetimeout: 10s
      dialtimeout: 10s
    http:
      addr: :5000
      relativeurls: false
      # set via environment variable
      # secret: placeholder
      auth:
       htpasswd:
         realm: registry-basic-realm
         path: /registry/passwd
    validation:
      disabled: true
    compatibility:
      schema1:
        enabled: true
  ctl-config.yml: |
    ---
    protocol: "http"
    port: 8080
    log_level: info
    registry_config: "/etc/registry/config.yml"
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-25T02:18:19Z"
  labels:
    app: registry
`
and a env `REGISTRY_STORAGE_AZURE_ACCOUNTKEY=123456`

 docker client version：

`Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:43 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
`
use docker command ` docker push image`

**Comment by bad2cat** [comment]
ok，my registry deploy on k8s，use image is docker pull distribution/distribution:edge

there is my configuration:

apiVersion: v1
data:
  config.yml: |
    version: 0.1
    log:
      level: info
      fields:
        service: registry
    storage:
      azure:
        accountname: ***
        container: ***
        realm: core.chinacloudapi.cn
      cache:
        layerinfo: redis
      maintenance:
        uploadpurging:
          enabled: false
      delete:
        enabled: true
      redirect:
        disable: true
    redis:
      addr: localhost:6379
      db: 13
      password: ******
      readtimeout: 10s
      writetimeout: 10s
      dialtimeout: 10s
    http:
      addr: :5000
      relativeurls: false
      # set via environment variable
      # secret: placeholder
      auth:
       htpasswd:
         realm: registry-basic-realm
         path: /registry/passwd
    validation:
      disabled: true
    compatibility:
      schema1:
        enabled: true
  ctl-config.yml: |
    ---
    protocol: "http"
    port: 8080
    log_level: info
    registry_config: "/etc/registry/config.yml"
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-25T02:18:19Z"
  labels:
    app: registry

and a env REGISTRY_STORAGE_AZURE_ACCOUNTKEY=123456

docker client version：

Client: Docker Engine - Community
Version: 20.10.2
API version: 1.41
Go version: go1.13.15
Git commit: 2291f61
Built: Mon Dec 28 16:17:43 2020
OS/Arch: linux/amd64
Context: default
Experimental: true

Server: Docker Engine - Community
Engine:
Version: 20.10.2
API version: 1.41 (minimum version 1.12)
Go version: go1.13.15
Git commit: 8891c58
Built: Mon Dec 28 16:15:19 2020
OS/Arch: linux/amd64
Experimental: false
containerd:
Version: 1.4.3
GitCommit: 269548fa27e0089a8b8278fc4fc781d7f65a939b
runc:
Version: 1.0.0-rc92
GitCommit: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
docker-init:
Version: 0.19.0
GitCommit: de40ad0

use docker command docker push image

**Comment by bad2cat** [comment]
@shizhMSFT
ok，my registry deploy on k8s，use image is docker pull distribution/distribution:edge

there is my configuration:

```
apiVersion: v1
data:
  config.yml: |
    version: 0.1
    log:
      level: info
      fields:
        service: registry
    storage:
      azure:
        accountname: ***
        container: ***
        realm: core.chinacloudapi.cn
      cache:
        layerinfo: redis
      maintenance:
        uploadpurging:
          enabled: false
      delete:
        enabled: true
      redirect:
        disable: true
    redis:
      addr: localhost:6379
      db: 13
      password: ******
      readtimeout: 10s
      writetimeout: 10s
      dialtimeout: 10s
    http:
      addr: :5000
      relativeurls: false
      # set via environment variable
      # secret: placeholder
      auth:
       htpasswd:
         realm: registry-basic-realm
         path: /registry/passwd
    validation:
      disabled: true
    compatibility:
      schema1:
        enabled: true
  ctl-config.yml: |
    ---
    protocol: "http"
    port: 8080
    log_level: info
    registry_config: "/etc/registry/config.yml"
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-25T02:18:19Z"
  labels:
    app: registry
```
and a env REGISTRY_STORAGE_AZURE_ACCOUNTKEY=123456

Docker version：

```
Client: Docker Engine - Community
Version: 20.10.2
API version: 1.41
Go version: go1.13.15
Git commit: 2291f61
Built: Mon Dec 28 16:17:43 2020
OS/Arch: linux/amd64
Context: default
Experimental: true

Server: Docker Engine - Community
Engine:
Version: 20.10.2
API version: 1.41 (minimum version 1.12)
Go version: go1.13.15
Git commit: 8891c58
Built: Mon Dec 28 16:15:19 2020
OS/Arch: linux/amd64
Experimental: false
containerd:
Version: 1.4.3
GitCommit: 269548fa27e0089a8b8278fc4fc781d7f65a939b
runc:
Version: 1.0.0-rc92
GitCommit: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
docker-init:
Version: 0.19.0
GitCommit: de40ad0
```
used docker command：

`docker push image
`
