### ISSUE TITLE
Support for multiple proxies

### ISSUE THREAD

**Issue by lengrongfu** [distribution/distribution#3725]
The current distribution only supports proxy requests for one domain name. Can we redesign the proxy to support multiple domain names?

If it is acceptable, I will design and develop.

**Comment by lengrongfu** [comment]
@milosgajdos

**Comment by Jamstah** [comment]
I think it's a sensible idea, I would suggest worrying down the design first before starting writing the code.

**Comment by Jamstah** [comment]
It was also raised here: https://github.com/distribution/distribution/issues/3253

**Comment by Jamstah** [comment]
> yes, I can design first, and at the same time want to know why this issue #3253 is not followed up

Because no one has implemented it yet :)

I don't think there is anything that doesn't match the project goals that would stop it being implemented. Really, either this issue or that one should be closed as a duplicate.

**Comment by lengrongfu** [comment]
The proxy configuration is adjusted as follows：
```
proxy:
- name: k8s-proxy
  remoteurl: https://registry.k8s.io
  username: [username]
  password: [password]
- name: hub-proxy
  remoteurl: https://hub.docker.io
  username: [username]
  password: [password]
- name: /
  remoteurl: https://registry.private.io
  username: [username]
  password: [password]
```

Because we need to proxy multiple registries, we need to distinguish, add the `name` field as a distinction, and in order to be compatible with previous usage scenarios, you can configure a proxy with a name of `/`.

In use, the request address needs to be modified: e.g.
````
# Before using proxy
$ docker pull registry.k8s.io/pause:3.8
# After using proxy
$ docker pull registry.proxy.io/k8s-proxy/pause:3.8
or (this will walk the default proxy rule `/` )
$ docker pull registry.proxy.io/pause:3.8
````

**Comment by Jamstah** [comment]
One issue with that layout is that its not compatible with existing configuration files - the proxy stanza is a map not an array. I think it would be sensible to work out a way for existing configurations to work without modification, and also allow for an extended configuration.

Also, I would say that instead of `name` we should use `path` to be clear what the value will be used for.

If we're making this change, would we also want to be able to proxy a subset of a remote registry? I guess we wouldn't need to code it up immediately, but making sure that its easy to extend the configuration schema if we want it in the future seems sensible.

```
- path: ubunu-from-docker
  remoteurl: https://docker.io/ubuntu
  username: ...
  password: ...
```

**Comment by lengrongfu** [comment]
Regarding compatibility with past configurations, I don't have much idea.

because this structure changes too much, mapping from one `registry` to one `proxy` to one `registry` mapping multiple `proxy`, this change is too big. If you have a good idea, you can propose it.

If it is to follow the Proxy configuration in the form of an array, I agree to change the `name` to `path`.

Please, the idea of "proxy a subset of a remote registry" can be said in more detail.

**Comment by Jamstah** [comment]
We could use a different key, such as `proxies`, or `proxy-map`, something like that.

Or we could use:
```
proxy:
  mappings:
  - path: dockerhub
    remoteurl: https://hub.docker.io
```

And then if there is a remoteurl configured at the top level, we could map it to the path `/` by default.

**Comment by Jamstah** [comment]
> Please, the idea of "proxy a subset of a remote registry" can be said in more detail.

If we want to proxy just one organisation in dockerhub for example, like we want to proxy `docker.io/ubuntu` because we trust the owner of that organisation, but not the whole of `docker.io`.

So in my example:
```
- path: ubunu-from-docker
  remoteurl: https://docker.io/ubuntu
  username: ...
  password: ...
```

**Comment by lengrongfu** [comment]
> proxy:
>   mappings:
>   - path: dockerhub
>     remoteurl: https://hub.docker.io

I like this style.

**Comment by lengrongfu** [comment]
> > Please, the idea of "proxy a subset of a remote registry" can be said in more detail.
> 
> 
> 
> If we want to proxy just one organisation in dockerhub for example, like we want to proxy `docker.io/ubuntu` because we trust the owner of that organisation, but not the whole of `docker.io`.
> 
> 
> 
> So in my example:
> 
> ```
> 
> - path: ubunu-from-docker
> 
>   remoteurl: https://docker.io/ubuntu
> 
>   username: ...
> 
>   password: ...
> 
> ```

I agree with your long-term thinking on this issue.  

But I have some ideas about this configuration. 

There are often multiple organizations in dockerhub or other registries. If we have multiple organizations that can be trusted, such as ubuntu, centos, nginx, etc., the same proxy registry needs  Configure multiple configurations. We can add a field `subPath` here to record the trust organization? 
If there is no configuration, all pass by default, otherwise it will be released according to the configuration

```

- path: ubunu-from-docker
  remoteurl: https://docker.io
  subPath: 
   - ubuntu
   - nginx
  username: ...
  password: ...

```

**Comment by Jamstah** [comment]
Also, `subPath` might be better as `namespaces`, which I've seen used as a term for organising registries.

**Comment by lengrongfu** [comment]
> Also, `subPath` might be better as `namespaces`, which I've seen used as a term for organising registries.

Then the structure of this configuration is defined as follows

```yaml 

proxy:
  username: a
  password:a
  remoteurl: https://registry.k8s.com
  namespace:
  - k8s
  mappings:
  - path: dockerhub
    username: test
    password: test 
    remoteurl: https://hub.docker.com
    namespace:
    - centos
    - ubuntu
```
e.g. 
- before pull:`docker pull centos:7`
- proxy pull: `docker pull registry.proxy.com/dockerhub/centos:7` can success.

- proxy pull: `docker pull registry.proxy.com/dockerhub/nginx:1.23.0` can fail.

Url is `{domain}/{path}/{reponane}:{reporag}

**Comment by Jamstah** [comment]
Great!

Some more thoughts, would this be valid to be able to rename remote namespaces into the proxy?

```
proxy:
  mappings:
  - path: quay-ubi8
    username: a
    password: b
    remoteurl: https://quay.io/ubi8
```

And, shouldn't it be `namespaces` not just `namespace` because there can be multiple?

Overall though, it feel very flexible and configurable.

**Comment by lengrongfu** [comment]
> Great!
> 
> Some more thoughts, would this be valid to be able to rename remote namespaces into the proxy?
> 
> ```
> proxy:
>   mappings:
>   - path: quay-ubi8
>     username: a
>     password: b
>     remoteurl: https://quay.io/ubi8
> ```
> 
> And, shouldn't it be `namespaces` not just `namespace` because there can be multiple?
> 
> Overall though, it feel very flexible and configurable.

Yes, is `namespaces`, it should be plural not singular.

The introduction of `namespaces` is to record the trust organization, but where the `image URL` will be defined as the organization, the URL of the `image` is different.
e.g. 
- docker.io/library/centos:7
- docker.io/bitnami/centos-base-buildpack:7-r9
- test.registry.io/test1/test2/test3:v1

**Comment by Jamstah** [comment]
> The introduction of namespaces is to record the trust organization, but where the image URL will be defined as the organization, the URL of the image is different.

**Comment by Jamstah** [comment]
Oh, sorry, I was thinking that you might use both, it was really so you could organise the hierarchy differently on your local repo:

```yaml
proxy:
  username: a
  password:a
  remoteurl: https://registry.k8s.com
  namespace:
  - k8s
  mappings: 
  - path: quay-ubi8
    username: a
    password: b
    remoteurl: https://quay.io/ubi8
  - path: quay-ubi7
    username: a
    password: b
    remoteurl: https://quay.io/ubi7
    namespaces:
    - ubi-minimal
  - path: dockerhub
    username: test
    password: test 
    remoteurl: https://hub.docker.com
    namespace:
    - centos
    - ubuntu
```

So:
- `proxy.io/k8s/*` -> `registry.k8s.com/k8s/*`
- `proxy.io/quay-ubi8/*` -> `quay.io/ubi8/*`
- `proxy.io/quay-ubi7/ubi-minimal/*` -> `quay.io/ubi7/ubi-minimal/*`
- `proxy.io/dockerhub/centos/*` -> `hub.docker.com/centos/*`
- `proxy.io/dockerhub/ubuntu/*` -> `hub.docker.com/ubuntu/*`
