### ISSUE TITLE
Need skip for a certificate check in notifications

### ISSUE THREAD

**Issue by zebox** [distribution/distribution#3824]
I try use notifications hook with self-signed certificate, but when an event triggered registry service throw the error
```text
 x509: certificatesigned by unknown authority, retrying"
```
I tried use add certificate to trusted and update it with `update-certificate-ca` but it's no effect. Error still occur.
```bash
# update-certificate-ca
Warning! Cannot copy to bundle: /usr/local/share/ca-certificates/extra
WARNING: ca-cert-users.pem does not contain exactly one certificate or CRL: skipping
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
```
This is my config for notifications
```yml
notifications:
  events:
    includereferences: true
  endpoints:
    - name: my-notifier
      disabled: false
      url: https://notification-service/events
      headers:
        Authorization: [Basic YWRtaW46c3VwZXItc2VjcmV0] # 'admin:super-secret' base64 encoded string
      timeout: 1s
      threshold: 5
      backoff: 3s
      ignoredmediatypes:
        - application/octet-stream
      ignore:
        mediatypes:
          - application/octet-stream
```

In spite of this `push/pull` and `login` works without problems.

How can I skip security check for self-signed certificates in notifications?

Use docker image `registry:v2` `registry version="v2.8.1"`
