### ISSUE TITLE
garbage-collect does not purge unused layers

### ISSUE THREAD

**Issue by chrisbecke** [distribution/distribution#3851]
## Issue

I am trying to shrink a registry that has been in use for a while. The garbage-collect function is not working as expected as it leaves ~30k entries in the `_layers` for certain repositories.

I have run a regclient/regbot script that prunes old tags, and the repository being examined contains only ~55 tags. `--delete-untagged` is used to ensure each tag points to (at most) a single revision, so there are also only 55 entries in _manifests/revisions for the repository.

When I fetch one of the manifests referenced using the sha256 from _manifests/revisions I get a normal looking json manifest with about 10 layers.

## What I expect

Given 35 revisions, and manifests with 10 layers each, I expect, at most 350 entries in _layers/sha256 for this repository. Instead, there are 35k entries in _layers/sha256.

## Config

registry:2 is run as a container with the following config mounted. S3 storage is provided by Minio.

`etc/docker/registry/config.yml`
```yaml
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  delete:
    enabled: true
  s3:
    accesskey: REDACTED
    secretkey: REDACTED
    region: us-east-1
    regionendpoint: http://s3.example.com
    bucket: registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```
