### ISSUE TITLE
Unable to delete manifest or layer

### ISSUE THREAD

**Issue by AnnaGuzy** [distribution/distribution#3853]
### Configuration
Version: 2.8.1
```yaml
version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
proxy:
  remoteurl: https://xxxr.azurecr.io
  username: xxx
  password: xxx
```
---
### Repo steps
- Pulled manifest and all layers of chosen image
- Checked digest of manifest
- Tried deleting manifest by sending DELETE http://localhost:5000/v2/{repo}/manifests/sha256:{hash}
### Expected result
Received 202 Accepted
### Actual result
Received 405 Method Not Allowed
```json
{
    "errors": [
        {
            "code": "UNSUPPORTED",
            "message": "The operation is unsupported."
        }
    ]
}
```
### Remarks
I also tried removing just single layer of the image, without success.
I tried setting storage/delete/enabled setting by configuration file or by environment variable, doesn't seem to make any difference.
I noticed this warning in startup logs of registry
```
"Registry does not implement RempositoryRemover. Will not be able to delete repos and tags" go.version=go1.16.15 instance.id=bd08b1fe-3838-4f77-8a51-e6e4cd6b17ab service=registry version="v2.8.1+unknown"
```
Does it mean that whole delete feature is not implemented?
