### ISSUE TITLE
Azure Blob Storage: image upload fails with ErrorCode=DirectoryIsNotEmpty

### ISSUE THREAD

**Issue by rpr-github** [distribution/distribution#3922]
We are trying to use Azure Blob Storage Containers as storage for the registry (pod in AKS cluster). 
There seems to be an issue with deletion of non-empty directories. 

Registry configuration parameters:
```yaml
    - name: REGISTRY_STORAGE
      value: azure
    - name: REGISTRY_STORAGE_AZURE_ACCOUNTNAME
      valueFrom:
        secretKeyRef:
          key: accountName
          name: microservices-registry-azure-secret
    - name: REGISTRY_STORAGE_AZURE_ACCOUNTKEY
      valueFrom:
        secretKeyRef:
          key: accountKey
          name: microservices-registry-azure-secret
    - name: REGISTRY_STORAGE_AZURE_CONTAINER
      value: my-container-5
```

When uploading an image we get error messages like this:
```
 {"auth.user.name":"admin","go.version":"go1.16.15","http.request.host":"microservices-registry.my-helm.svc.cluster.local:5000",
 "http.request.method":"PUT",
 "http.request.uri":"/v2/busybox/blobs/uploads/1f992187-4e37-48bd-b0ac-7e94117c3f41?_state=Ogec...14ae7",
 "http.request.useragent":"docker/23    .0.4 go/go1.19.8 git-commit/cbce331 kernel/5.4.0-1098-azure os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \\(linux\\))",
 "level":"error",
 "msg":"unable to delete layer upload resources \"/docker/registry/v2/repositories/busybox/_uploads/1f992187-4e37-48bd-b0ac-7e94117c3f41\": azure: storage: service returned error: StatusCode=409,
 ErrorCode=DirectoryIsNotEmpty,
 ErrorMessage=This operation is not permitted on a non-empty directory.
 ...
 ```

The directory structure, however, exists in the Azure container: `/docker/registry/v2/repositories/busybox/`
