### ISSUE TITLE
Error when trying docker push a large layer 

### ISSUE THREAD

**Issue by hegedussz** [distribution/distribution#4048]
The docker push failed when the layer is larger than 1 GB.

**Solution**:

``` Gitlab -> Registry -> S3 (MiniO) ```

Settings:

**Gitlab:**

```
server {
  listen *:80;
  server_name  domain.ltd;
  server_tokens off; 
  return 301 https://$http_host:$request_uri;
  access_log  /var/log/gitlab/nginx/gitlab_registry_access.log;
  error_log   /var/log/gitlab/nginx/gitlab_registry_error.log;
}

server {

  listen *:5500 ssl http2;
  server_name  domain.ltd;
  server_tokens off; ## Don't show the nginx version number, a security best practice

  client_max_body_size 0;
  chunked_transfer_encoding off;

  ssl_certificate /home/git/data/certs/gitlab-certs.crt;
  ssl_certificate_key /home/git/data/certs/gitlab-certs.key;

  ssl_ciphers "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;
  ssl_session_cache  builtin:1000  shared:SSL:10m;
  ssl_session_timeout  5m;

  access_log  /var/log/gitlab/nginx/gitlab_registry_access.log;
  error_log   /var/log/gitlab/nginx/gitlab_registry_error.log;

  location / {
    proxy_set_header  Host              $http_host;   # required for docker client's sake
    proxy_set_header  X-Real-IP         $remote_addr; # pass on real client's IP
    proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header  X-Forwarded-Proto $scheme;
    proxy_read_timeout                  900;
    proxy_connect_timeout               900;

    chunked_transfer_encoding off;

    proxy_pass          http://registry:5000/;
  }

}
```
**Registry image**: registry:2.8.2
**Registry stoage values**:

```REGISTRY_STORAGE: s3
REGISTRY_STORAGE_DELETE_ENABLED: true
REGISTRY_STORAGE_S3_ACCESSKEY: xxxx
REGISTRY_STORAGE_S3_BUCKET: xxxx
REGISTRY_STORAGE_S3_CHUNKSIZE: 1036870912
REGISTRY_STORAGE_S3_FORCEPATHSTYLE: true
REGISTRY_STORAGE_S3_REGION: xxxx
REGISTRY_STORAGE_S3_REGIONENDPOINT: xxxx
REGISTRY_STORAGE_S3_SECRETKEY: xxxx
REGISTRY_STORAGE_S3_multipartcopychunksize: 536870912
REGISTRY_STORAGE_S3_multipartcopymaxconcurrency: 1000
REGISTRY_STORAGE_S3_multipartcopythresholdsize: 536870912
```

**MinIO ingress-nginx:**

```
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.global-static-ip-name: ""
    meta.helm.sh/release-name: minio
    meta.helm.sh/release-namespace: minio
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/client-max-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
```
