### ISSUE TITLE
docker registry not supporting GCS

### ISSUE THREAD

**Issue by mkoszut** [distribution/distribution#4057]
When I try to upgrade my docker registry from version 2.7 to 2.8 the error like below occurs. 

```
panic: StorageDriver not registered: gcs

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp({0xe5e8a0?, 0xc0003f4bd0?}, 0xc0003b7880)
	github.com/docker/distribution/registry/handlers/app.go:127 +0x2411
github.com/docker/distribution/registry.NewRegistry({0xe5e8a0?, 0xc0003f41b0?}, 0xc0003b7880)
	github.com/docker/distribution/registry/registry.go:161 +0x145
github.com/docker/distribution/registry.glob..func1(0xc0000341a0?, {0xc0003096e0, 0x1, 0x1})
	github.com/docker/distribution/registry/registry.go:119 +0x18f
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x1369f60, {0xc0003096a0?, 0x2?, 0x2?})
	github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x44f
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x136a100)
	github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0xaa
main.main()
	github.com/docker/distribution/cmd/registry/main.go:23 +0x25
```

my docker registry configuration

```
version: 0.1
log:
  fields:
    service: registry
  level: debug
storage:
  cache:
    blobdescriptor: redis
  gcs:
    bucket: bucket-name
    keyfile: /auth/auth.json
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
redis:
  addr: redis:6379
  db: 1
  dialtimeout: 1s
  readtimeout: 1s
  writetimeout: 1s
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s
```
