### ISSUE TITLE
Unable to upload images to private registry via github actions

### ISSUE THREAD

**Issue by tonydawhale** [distribution/distribution#4145]
I am unable to upload my images that are created in a github action to my private registry. The nginx reverse proxy config has a `client_max_body_size 0;` Below is my github workflow
```yml
  docker:
    name: deploy image to docker registry
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'pull_request'
    needs: [yarn, eslint, prettier, typescript]
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to Docker Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/sbm-v3:latest
```
![image](https://github.com/distribution/distribution/assets/75507889/2572a5a0-7f69-4763-a383-67876def4fd0)

There is nothing wrong in my nginx logs either, no indication of a 413 error. https://hst.sh/exofadovut.yaml
Any tips?
