### ISSUE TITLE
Unable to enable proxy via config.yml, but it works via REGISTRY_PROXY_REMOTEURL

### ISSUE THREAD

**Issue by akomakom** [distribution/distribution#4151]
Following instructions at https://docs.docker.com/docker-hub/mirror/#configure-the-cache I added a stanza to my config file and mounted it as follows:

`docker run -d -p 5000:5000 --restart always --name registry -v /LOCAL/PATH/docker-registry-config.yml:/etc/docker/registry/config.yml registry:2`

docker-registry-config.yml:
```yaml
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
proxy:
  remoteUrl: https://registry-1.docker.io
```
Note that I have tried with and without credentials in the proxy section.

After configuring docker with `"registry-mirrors": ["http://localhost:5000"]`, `docker pull alpine` results in 404s logged in the registry container.  No attempt is made to pull them from upstream.  Removing the `proxy` section from the yaml file makes no difference.

When running using environment variables (which I accidentally found by searching through issues), proxy works fine:
`docker run -d --name registry --restart=always -p 5000:5000   -e REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io registry:2`

Registry now caches the image:

```
$ curl http://localhost:5000/v2/_catalog
{"repositories":["library/alpine"]}
```

I'm guessing that etiher the docs are wrong or this is a regression?

* registry image: ff1857193a0b
* Docker version 24.0.7, build afdd53b
* Platform: Ubuntu 22.04

**Comment by milosgajdos** [comment]
Well, from the first look I can see you have a typo in the config key.

Yours:
```
remoteUrl
```

Required:
```
remoteurl
```

NOTE: `Url` vs _all lowercase_ `url`

**Comment by akomakom** [comment]
That would do it :)   Thanks!

Is there a reference for all the environment variable params for this image?

**Comment by milosgajdos** [comment]
> Is there a reference for all the environment variable params for this image?

It follows a convention that walks the `YAML` tree that starts with `REGISTRY_` as the root node. 

In other words, as you walk down the tree you just keep appending the config options:

```
REGISTRY_PROX_REMOTEURL
```

is equivalent to 

```yaml
"root" (REGISTRY_)
  proxy: (_PROXY_)
    remoteuur: (_REMOTEURL)
```
