### ISSUE TITLE
Push hangs at first layer

### ISSUE THREAD

**Issue by mayorovp** [distribution/distribution#4220]
### Description

I cannot push anything on private registry, like this:

```
root@gateway:/home/ubuntu# docker push registry.mcs.local/alpine
Using default tag: latest
The push refers to repository [registry.mcs.local/alpine]
5af4f8f59b76: Pushing [=======>                                           ]  1.065MB/7.377MB
```

### Reproduce

1. start registry with image distribution/distribution:edge using s3 from vk cloud
2. try to push something to it
3. see nothing on docker side, and infinite s3/ListParts requests on registry side in logs (>10 requests per second)

### Expected behavior

Push is successfull. Or returned useful error message.
At least write some useful error message to logs!

### registry version

registry:2.8.3, distribution/distribution:edge

### Additional Info

My registry configuration:

```yaml
version: 0.1
log:
  level: debug
storage:
  s3:
    accesskey: [redacted]
    secretkey: [redacted]
    region: kz-ast
    regionendpoint: https://hb.kz-ast.vkcs.cloud
    bucket: registry-images
    rootdirectory: /own
    loglevel: debug
  redirect:
    disable: false
  delete:
    enabled: false
  cache:
    blobdescriptor: inmemory
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: false
http:
  addr: 0.0.0.0:80
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```

[Logs in attachment](https://github.com/distribution/distribution/files/13777229/registry-log.txt)
