### ISSUE TITLE
Docker registry as a pull through cache with AWS ECR repository

### ISSUE THREAD

**Issue by fti-sshendre** [distribution/distribution#4252]
### Description

We are hosting a private docker registry in AWS ECR and we have development team in several sites around the world.
Having a docker pull through cache would help to reduce the time each engineer spend trying to pull down the image
from the AWS cloud to their local site (basically, all engineer at one site will share the same cache so if an
image is already pulled, it will be served directly from the local cache).

Lets consider there are two machines as follows:
- Machine A (Has a local registry)
- Machine B (Client machine, from where we will pull an images)

I am trying to setup an environment as follows:
- Docker pull request will be send to "Machine A" (local registry) from "Machine B" (client machine).
- I am expecting that, "Machine A" should check the differences between an images from the local registry and remote
repositories (AWS ECR Private Registry in my case).
- If there is any difference in requested image then it will fetch from remote repository otherwise it will pull from local registry.

[Diagramatic view is attached for reference]
[Diagram](https://i.stack.imgur.com/E6qRD.png)

I have tried following approaches to make it work according to [docker documentation](https://docs.docker.com/docker-hub/mirror/):
- Added following configuration in `/etc/registry/config.yml` in "Machine A" (local registry):
```
proxy:
    remoteurl: https://<your-ecr-registry>.dkr.ecr.<region>.amazonaws.com
    username: <username>
    password: <your-ecr-authorization-token>
```

- Added following configuration in `/etc/docker/daemon.json` in "Machine B" (client machine):
```
{
    "registry-mirror": ["https://<my-docker-mirror-host>"]
}
```

After using above approach, I am getting `manifest unknown error` on "Machine B" (client machine). It means, my local registry is unable to fetch requested docker image from AWS ECR (remote repository).

Any related information or insights related to the steps outlined above would be highly beneficial for a comprehensive understanding and troubleshooting of the proxy configuration in the Docker environment for ECR Private Registry.

I found some issues reported regarding above. But unfortunately, I did not find any solution to achieve my requirement.

I have attached some reference links:
- https://github.com/distribution/distribution/issues/922#issuecomment-140605929

**Comment by igordrnobrega** [comment]
@fti-sshendre, any news on this? Did you get help, or could you solve it by yourself?

**Comment by erfanw** [comment]
@fti-sshendre @igordrnobrega Private ECR is authenticated through basic-auth, which is not supported with registry:2.
I tested registry:3 which does support basic auth, and it worked with ECR

**Comment by ubivent-seuffert** [comment]
> @fti-sshendre @igordrnobrega Private ECR is authenticated through basic-auth, which is not supported with registry:2. I tested registry:3 which does support basic auth, and it worked with ECR

@erfanw could you kindly share a working example config for a pull-through cache for AWS ECR with registry:3?

**Comment by erfanw** [comment]
@ubivent-seuffert Hello, I deployed using registry 3.0.0-beta.1, and give username/password as usual to my private ECR.

**Comment by gabordk** [comment]
> @erfanw how do you manage the ECR auth token expiration?

It's a bit complex but doable, my setup is done with K8S and Helm:
- you have to use the external secrets operator to create and maintain a secret which contains valid ECR credentials all the time
- you need to configure the registry deployment to read the config.yml externally from a configmap
- you need to add an init container for the registry deployment, which reads the ECR secret and updating the password in the configmap
- you need to use Reloader to trigger the registry deployment to do a rolling restart when the ECR secret is updated

**Comment by snavarro-factorial** [comment]
> > @erfanw how do you manage the ECR auth token expiration?
> 
> It's a bit complex but doable, my setup is done with K8S and Helm:
> 
> * you have to use the external secrets operator to create and maintain a secret which contains valid ECR credentials all the time
> * you need to configure the registry deployment to read the config.yml externally from a configmap
> * you need to add an init container for the registry deployment, which reads the ECR secret and updating the password in the configmap
> * you need to use Reloader to trigger the registry deployment to do a rolling restart when the ECR secret is updated

Hi!
I'm dwelving into the same issue right now. Would you mind to share your deployment yamls? I'm a bit stuck into making the whole picture to work and I'd love the push.
Thanks a lot!

**Comment by Tak-MK** [comment]
> > @erfanw how do you manage the ECR auth token expiration?
> 
> It's a bit complex but doable, my setup is done with K8S and Helm:
> 
> * you have to use the external secrets operator to create and maintain a secret which contains valid ECR credentials all the time
> * you need to configure the registry deployment to read the config.yml externally from a configmap
> * you need to add an init container for the registry deployment, which reads the ECR secret and updating the password in the configmap
> * you need to use Reloader to trigger the registry deployment to do a rolling restart when the ECR secret is updated

Hi!
I'm dwelving into the same issue right now. Would you mind to share your deployment yamls? I'm a bit stuck into making the whole picture to work and I'd love the push.
Thanks a lot!

**Comment by andromeda306** [comment]
> [@ubivent-seuffert](https://github.com/ubivent-seuffert) Hello, I deployed using registry 3.0.0-beta.1, and give username/password as usual to my private ECR.

how did you manage to configure this to work?

**Comment by jocado** [comment]
I was able to make this work with ECS, using reg version 3.0.0, and two different docker credential helpers [ as referenced [above](https://github.com/distribution/distribution/issues/4252#issuecomment-2547712665) ].

One of the credential helpers is a custom one, but I can provide a hopefully one useful example using the other one, which is arguably the most relevant one for this issue, `docker-credential-ecr-login` from [here](https://github.com/awslabs/amazon-ecr-credential-helper) 

For this you need an AWS key, and the correct IAM policy associated with it [ more on that below ].

 Add the required components for `docker-credential-ecr-login` to the docker image [ the compiled binary, configs for `.docker/config`  and  `.aws/credentials` ].  I created a new registry docker image which contains the binary and docker config, and bind mounted in the aws credential at run time.  See the configuration instruction [here](https://github.com/awslabs/amazon-ecr-credential-helper?tab=readme-ov-file#configuration) for general docker-credential-ecr-login setup tips.

Then you need to add something similar as below to your registry config:
```
proxy:
  remoteurl: https://my-registry.something:1234
  exec:
    command: /usr/bin/docker-credential-ecr-login
    # set whatever you think is appropriate here
    lifetime: 30m
  # 2 weeks
  ttl: 336h
```

Details of the config options can be found here: https://distribution.github.io/distribution/about/configuration/#proxy

Once I had that setup, it still wasn't quite working, I was getting errors similar to the following on docker pull:
```
ERRO[0005] response completed with error                 err.code="blob unknown" err.detail="sha256:ad0adaa269c64243d1d7736cfcb664767b675f1ddc291a889df6c2f123456789" err.message="blob unknown to registry"
```

What I eventually found was that the AIM policy associated with the access key had to be correct:

You need to allow all of:
```
            "Action": [
                "ecr:GetAuthorizationToken",
                "ecr:GetDownloadUrlForLayer",
                "ecr:BatchCheckLayerAvailability",
                "ecr:BatchGetImage"
            ]
```

Then it started working.

You can further restrict the actions to particular resource paths, but I believe the token permission needs to be left wide:

```
            "Effect": "Allow",
            "Action": [
                "ecr:GetDownloadUrlForLayer",
                "ecr:BatchGetImage",
                "ecr:BatchCheckLayerAvailability"
            ],
            "Resource": ""arn:aws:ecr:*:123456789012:repository/*""
---8<---
            "Effect": "Allow",
            "Action": [
                "ecr:GetAuthorizationToken"
            ],
            "Resource": "*"
```

Hope that helps someone.

**Comment by wnark** [comment]
@jocado 
Hello, I tried accelerating the public mirror site and it doesn't seem to work!
just like:
```
docker pull public.ecr.aws/docker/library/python:3.12
```

config:
```
version: 0.1
log:
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory   
    blobdescriptorsize: 10000
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: false
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['*']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization', 'Accept', 'Cache-Control']
    Access-Control-Max-Age: [1728000]
    Access-Control-Allow-Credentials: [true]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']

health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3

proxy:
  remoteurl: https://public.ecr.aws
  username: 
  password:
  ttl: 168h
```
