### ISSUE TITLE
After configuring authentication,  can log in normally, but when pulling the image, you are prompted with a 401 error.

### ISSUE THREAD

**Issue by dqzboy** [distribution/distribution#4419]
### Description

After setting the registry as a proxy and configuring authentication through htpasswd, and then configuring the daemon.json on other servers to specify registry-mirrors, can log in normally using docker login, but you are unable to download images when you try to docker pull. The registry logs are as follows:

```
time="2024-07-24T05:37:08.758499096Z" level=info msg="response completed" auth.user.name=dqzboy go.version=go1.22.4 http.request.host=hub.dockerhub.xyz http.request.id=e001a4a4-fd17-4fa7-b341-b408fcd59cce http.request.method=GET http.request.remoteaddr=10.138.136.123 http.request.uri=/v2/ http.request.useragent="docker/25.0.3 go/go1.21.6 git-commit/f417435 kernel/5.14.0-202.el9.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/25.0.3 \\(linux\\))" http.response.contenttype=application/json http.response.duration=3.103692ms http.response.status=200 http.response.written=2 instance.id=00590a0e-122e-49ba-a6fb-eeaa64097990 service=registry version=3.0.0-beta.1
172.21.0.1 - - [24/Jul/2024:05:37:08 +0000] "GET /v2/ HTTP/1.0" 200 2 "" "docker/25.0.3 go/go1.21.6 git-commit/f417435 kernel/5.14.0-202.el9.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/25.0.3 \\(linux\\))"
time="2024-07-24T05:37:34.548876925Z" level=warning msg="error authorizing context: basic authentication challenge for realm \"basic-realm\": invalid authorization credential" go.version=go1.22.4 http.request.host=hub.dockerhub.xyz http.request.id=1b4d348c-28a0-46c7-bda0-0eaa9cb9e45b http.request.method=GET http.request.remoteaddr=10.138.136.123 http.request.uri=/v2/ http.request.useragent="docker/25.0.3 go/go1.21.6 git-commit/f417435 kernel/5.14.0-202.el9.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/25.0.3 \\(linux\\))" instance.id=00590a0e-122e-49ba-a6fb-eeaa64097990 service=registry version=3.0.0-beta.1
172.21.0.1 - - [24/Jul/2024:05:37:34 +0000] "GET /v2/ HTTP/1.0" 401 87 "" "docker/25.0.3 go/go1.21.6 git-commit/f417435 kernel/5.14.0-202.el9.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/25.0.3 \\(linux\\))"
```

### Reproduce

1. Configure the registry as a proxy for Docker Hub.

config.yml
```
version: 0.1
log:
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory   
    blobdescriptorsize: 10000
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: false
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]

health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3

proxy:
  remoteurl: https://registry-1.docker.io
  username: 
  password:
  ttl: 168h  

auth:
  htpasswd:
    realm: basic-realm
    path: /auth/htpasswd
```

2. Generate keys using htpasswd and mount them, then start the service.

```
htpasswd -Bbn user passwd > htpasswd
```
- docker-compose.yaml

```
services:
  docker:
    container_name: docker
    image: distribution:3.0.0-beta.1
    restart: always
    volumes:
      - ./registry/data:/var/lib/registry
      - ./config.yml:/etc/distribution/config.yml
      - ./htpasswd:/auth/htpasswd
    ports:
      - 53000:5000
    networks:
      - registry-net
```

3. Configure the daemon.json to specify the distribution service address, restart Docker, and log in through docker login.

- When executing docker login, the registry logs are as follows:
![image](https://github.com/user-attachments/assets/150ab172-2362-4342-8684-59243c88c002)

![image](https://github.com/user-attachments/assets/f5eac3e6-15ec-44ff-8154-3625bad321c6)

- When executing docker pull, the registry logs are as follows:

![image](https://github.com/user-attachments/assets/220dfcfe-ade2-4d78-9375-9e520faf0cb2)

When executing `docker pull`, adding the registry address allows for normal image pulling, but this does not meet the expected outcome.

### Expected behavior

After configuring the authentication and successfully logging in, can normally pull images without the need to specify the registry address when executing docker pull.

### registry version

registry version 3.0.0-beta.1
Docker version 26.1.4
