### ISSUE TITLE
Support `Virtual Hosted Style` s3 complicated storage servers.

### ISSUE THREAD

**Issue by zzjin** [distribution/distribution#4452]
### Description

When using latest 3.0.0 release. I cannot set storage s3 to use "Vitual Hosted Style" accessed.

config:
```yaml
storage:
  s3:
    accesskey: xxx
    secretkey: xxx
    region: no-use
    regionendpoint: https://bucket-name.oss-ap-1.internal.example.com
    bucket: bucket-name
```

I have one s3 complicated storage server that onyl support access buckets via `Virtual Hosted Style` access.

When push to registry, shows this error:
```
s3aws: SecondLevelDomainForbidden: Please use virtual hosted style to access.
```

Change config to neither:
```yaml
    regionendpoint: https://bucket-name.oss-ap-1.internal.example.com
    bucket: ''
```
nor
```yaml
    regionendpoint: https://oss-ap-1.internal.example.com
    bucket: 'bucket-name'
```
all do not work.

How can I configure storage s3 to use `Virtual Hosted Style` access?
Maybe related to: https://github.com/distribution/distribution/pull/3131

---
Also tested with latest codes using [redirect](https://github.com/distribution/distribution/blob/main/registry/storage/driver/middleware/redirect/middleware.go) middleware, but still not work
```yaml
storage:
  s3:
    accesskey: xxx
    secretkey: xxx
    region: no-use
    regionendpoint: https://oss-ap-1.internal.example.com
    bucket: bucket-name
middleware:
  storage:
    - name: redirect
      options:
        baseurl: https://bucket-name.oss-ap-1.internal.example.com
```

**Comment by zzjin** [comment]
> That should be enabled by setting `forcepathstyle` in S3 driver to false, which should be the default 🤔
> 
> https://github.com/distribution/distribution/blob/ba2841b0ce1e09ab7cacddc0a003d5daac5c5a85/registry/storage/driver/s3-aws/s3.go#L208

There seems be some kind of bug when enable this:
```yaml
storage:
  s3:
    region: no-use
    regionendpoint: https://bucket-name.oss-ap-1.internal.example.com
    bucket: bucket-name
    forcepathstyle: true
```
witch result in error still exists.

It seems that registry push objects to `s3://bucket-name/bucket-name/${regsitry_info}`, but still get object from `s3://bucket-name/${registry_name}`.

As I cannot set `bucket` to empty string, there is no more method to test it.
