### ISSUE TITLE
Server does not comply W3C preflight-request specification

### ISSUE THREAD

**Issue by Joxit** [distribution/distribution#4458]
### Description

As stated in the [CORS Protocol](https://fetch.spec.whatwg.org/#http-cors-protocol), in a preflight request, i.e. on an OPTIONS request, the server should return specific headers and 200 or 204 status code.

The headers can be configured with the configuration file, however, the server is always returning an `HTTP/1.1 401 Unauthorized` status code.

from [3.2.3. HTTP responses](https://fetch.spec.whatwg.org/#http-responses):
> A successful HTTP response, i.e., one where the server developer intends to share it, to a [CORS request](https://fetch.spec.whatwg.org/#cors-request) can use any [status](https://fetch.spec.whatwg.org/#concept-status), as long as it includes the [headers](https://fetch.spec.whatwg.org/#concept-header) stated above with [values](https://fetch.spec.whatwg.org/#concept-header-value) matching up with the request.
>
> A successful HTTP response to a [CORS-preflight request](https://fetch.spec.whatwg.org/#cors-preflight-request) is similar, except it is restricted to an [ok status](https://fetch.spec.whatwg.org/#ok-status), **e.g., 200 or 204**.
>
> Any other kind of HTTP response is not successful and will either end up not being shared or fail the [CORS-preflight request](https://fetch.spec.whatwg.org/#cors-preflight-request). Be aware that any work the server performs might nonetheless leak through side channels, such as timing. If server developers wish to denote this explicitly, the 403 [status](https://fetch.spec.whatwg.org/#concept-status) can be used, coupled with omitting the relevant [headers](https://fetch.spec.whatwg.org/#concept-header).

### Reproduce

Using the configuration:
```yml
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
auth:
  htpasswd:
    realm: basic-realm
    path: /etc/docker/registry/htpasswd
```

1. docker run -ti --rm -p 5000:5000 -v $(pwd)/config.yml:/etc/docker/registry/config.yml registry:2.8.3 
2. `curl -vv -X OPTIONS http://127.0.0.1:5000/v2/_catalog`

### registry version

registry github.com/docker/distribution 2.8.3
