### ISSUE TITLE
Docker login - invalid authorization credential - running in k8

### ISSUE THREAD

**Issue by psimms-cs** [distribution/distribution#4462]
### Description

I am setting up a registry in k8 with basic authentication,  I can authenticate to the url endpoint through curl but I can't login to the registry to use it 

Am I missing something here? I can't seem to figure out why I can't login to the registry

Login attempt
```
> docker login -u testuser distribution-registry.domain
Password:
Error response from daemon: login attempt to https://distribution-registry.domain/v2/ failed with status: 401 Unauthorized
```

Error
```
error authorizing context: basic authentication challenge for realm "Registry Realm": invalid authorization credential"
```

Curl successful
```
> curl -v https://distribution-registry.domain -u testuser:testpassword
* Host distribution-registry.domain:443 was resolved.
* IPv6: (none)
* IPv4: 10.0.0.1
*   Trying 10.0.0.1:443...
* Connected to distribution-registry.domain (10.0.0.1) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384 / [blank] / UNDEF
* ALPN: server accepted h2
* Server certificate:
......
*  SSL certificate verify ok.
* using HTTP/2
* Server auth using Basic with user 'testuser'
* [HTTP/2] [1] OPENED stream for https://distribution-registry.domain/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: distribution-registry.domain]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [authorization: Basic dGVzdHVzZXI6dGVzdHBhc3N3b3Jk]
* [HTTP/2] [1] [user-agent: curl/8.7.1]
* [HTTP/2] [1] [accept: */*]
> GET / HTTP/2
> Host: distribution-registry.domain
> Authorization: Basic dGVzdHVzZXI6dGVzdHBhc3N3b3Jk
> User-Agent: curl/8.7.1
> Accept: */*
>
* Request completely sent off
< HTTP/2 200
< date: Thu, 12 Sep 2024 11:25:54 GMT
< content-length: 0
< cache-control: no-cache
< strict-transport-security: max-age=31536000; includeSubDomains
<
* Connection #0 to host distribution-registry.domain left intact
```

### Reproduce

Setup registry in k8s
Use basic auth
Use domain certs
Docker login fails

### Expected behavior

Can login via docker - More insight in the error would also be helpful

### registry version

registry github.com/docker/distribution 2.8.3

### Additional Info

k8 manifest

```
apiVersion: v1
kind: Namespace
metadata:
  name: distribution-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: distribution-registry
  namespace: distribution-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distribution-registry
  template:
    metadata:
      labels:
        app: distribution-registry
    spec:
      containers:
      - name: distribution-registry
        image: registry:2
        ports:
        - containerPort: 443
        env:
        - name: REGISTRY_HTTP_HOST
          value: "https://distribution-registry.domain"
        - name: REGISTRY_AUTH
          value: "htpasswd"
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: "/auth/auth"
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: "Registry Realm"
        - name: REGISTRY_HTTP_ADDR
          value: "0.0.0.0:443"
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: "/certs/tls.crt"
        - name: REGISTRY_HTTP_TLS_KEY
          value: "/certs/tls.key"
        - name: REGISTRY_LOG_LEVEL
          value: "debug"
        volumeMounts:
        - name: basic-auth
          mountPath: "/auth"
          readOnly: true
        - name: distribution-registry-tls-secret
          mountPath: "/certs"
          readOnly: true
      volumes:
      - name: basic-auth
        secret:
          secretName: basic-auth
      - name: distribution-registry-tls-secret
        secret:
          secretName: distribution-registry-tls-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: distribution-registry
data:
  auth: >-
    dGVzdHVzZXI6JDJ5JDA1JFFkRGIydS9PaXMxanFaRVNRYjEzRWVKcmJZWXpaZGlBTGxibzlmWHdPNHNad0tnLjhOUXBxCgo=
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: distribution-registry-service
  namespace: distribution-registry
spec:
  selector:
    app: distribution-registry
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: distribution-registry-tls-secret
  namespace: distribution-registry
data:
  tls.crt: >-
    base64-secret
  tls.key: >-
    base64-secret
type: kubernetes.io/tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: distribution-registry-ingress
  namespace: distribution-registry
  labels:
    component: distribution-registry-nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-ssl-secret: distribution-registry/distribution-registry-tls-secret
    nginx.ingress.kubernetes.io/proxy-ssl-verify: 'on'
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Registry Realm"
spec:
  ingressClassName: ingress-nginx
  tls:
  - hosts:
    - distribution-registry.domain
    secretName: distribution-registry-tls-secret
  rules:
    - host: distribution-registry.domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: distribution-registry-service
                port:
                  number: 443
```
