### ISSUE TITLE
How to set HTTP_PROXY and NO_PTOXY ?

### ISSUE THREAD

**Issue by seepine** [distribution/distribution#4490]
### Description

I run `registry:2` with docker compose, but the `NO_PROXY` not work

```sh
dockerhub-1  | time="2024-10-18T07:44:22.901234529Z" level=info msg="Starting cached object TTL expiration scheduler..." go.version=go1.20.8 instance.id=1dbc9ac4-2b94-4d2e-828a-0d5a78f91c18 service=registry version=2.8.3 
dockerhub-1  | panic: Get "https://registry-1.docker.io/v2/": read tcp 172.28.0.5:38194->192.168.2.1:7890: read: connection reset by peer
dockerhub-1  | 
dockerhub-1  | goroutine 1 [running]:
dockerhub-1  | github.com/docker/distribution/registry/handlers.NewApp({0xf29128?, 0xc000618150?}, 0xc000488700)
dockerhub-1  |  github.com/docker/distribution/registry/handlers/app.go:324 +0x1bcd
dockerhub-1  | github.com/docker/distribution/registry.NewRegistry({0xf29128?, 0xc000487b00?}, 0xc000488700)
dockerhub-1  |  github.com/docker/distribution/registry/registry.go:161 +0x145
dockerhub-1  | github.com/docker/distribution/registry.glob..func1(0xc0001a0160?, {0xc00040cbd0, 0x1, 0x1})
dockerhub-1  |  github.com/docker/distribution/registry/registry.go:119 +0x18f
dockerhub-1  | github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x14ae1e0, {0xc00040cb90?, 0x2?, 0x2?})
dockerhub-1  |  github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x44f
dockerhub-1  | github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x14ae380)
dockerhub-1  |  github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0xaa
dockerhub-1  | main.main()
dockerhub-1  |  github.com/docker/distribution/cmd/registry/main.go:23 +0x25
```

### Reproduce

Run `docker compose up`

```yml
services:
  hub:
    image: registry:2
    volumes:
      - ./data:/var/lib/registry
      - ./config-docker.yml:/etc/docker/registry/config.yml
    environment:
      - HTTP_PROXY=http://192.168.2.1:7890
      - HTTPS_PROXY=http://192.168.2.1:7890
      - NO_PROXY="localhost,127.0.0.1,172.28.0.5,172.28.0.6,172.0.0.0/8"
```

### Expected behavior

It can work with `HTTP_PROXY` and `NO_PROXY`

### registry version

registry:2.8.3
