### ISSUE TITLE
Ignoring unrecognized environment variable REGISTRY_REDIS_PASSWORD

### ISSUE THREAD

**Issue by legolego621** [distribution/distribution#4512]
### Description

When trying to replace the redis.password configuration via the REGISTRY_REDIS_PASSWORD ENV, it is not actually replaced.
I see this log 

```
time="2024-11-19T11:39:27Z" level=warning msg="Ignoring unrecognized environment variable REGISTRY_REDIS_PASSWORD"`
```

### Reproduce

1. use registry version **3.0.0-rc.1**
2. use this config of distribution
```
    storage:
      cache:
        blobdescriptor: redis
    redis:
      addrs: [registry-redis-master:6379]
      ## override config with env REGISTRY_REDIS_PASSWORD
      password: replaced-with-env
      db: 0
      dialtimeout: 10ms
      readtimeout: 10ms
      writetimeout: 10ms
      pool:
        maxidle: 16
        maxactive: 64
        idletimeout: 300s
      tls:
        enabled: false
```
3. run registry with env configuration
```
    env -i \
      REGISTRY_REDIS_PASSWORD="my_secret_of_redis_password" \
    /bin/registry serve /etc/application/secret.yaml
```
4. try pushing image and check logs of distribution
```
{"blob":"sha256:cd43ca3ebe4acdc90375a2ec6f1945e3eee504981eb31b00a7746d041189b57c","error":"WRONGPASS invalid username-password pair or user is disabled.","go.version":"go1.23.2","http.request.host":"localhost:5000","http.request.id":"86e75373-871d-4a9f-a083-12fcda8292bf","http.request.method":"GET","http.request.remoteaddr":"[::1]:47182","http.request.uri":"/v2/dev/registry01/nginx/blobs/sha256:cd43ca3ebe4acdc90375a2ec6f1945e3eee504981eb31b00a7746d041189b57c","http.request.useragent":"go-containerregistry/v0.19.2","instance.id":"c5c7f0d6-6f47-40f9-b0f5-24b03c164d5f","level":"error","msg":"error from cache stat(ing) blob","time":"2024-11-19T11:57:19.311598093Z","vars.digest":"sha256:cd43ca3ebe4acdc90375a2ec6f1945e3eee504981eb31b00a7746d041189b57c","vars.name":"dev/registry01/nginx","version":"3.0.0-rc.1"}
```
5. check blobs in redis. It will be empty.
```
localhost:6379> KEYS *
(empty array)
```

### Expected behavior

ENV REGISTRY_REDIS_PASSWORD will replace configuration redis.password

### registry version

github.com/distribution/distribution/v3 3.0.0-rc.1
