### ISSUE TITLE
Docker push fails with S3 backend (SeaweedFS with vSphere CSI) with "Unexpected EOF"

### ISSUE THREAD

**Issue by mdzhigarov** [distribution/distribution#4584]
### Description

I have deployed Distribution in my k8s cluster alongside SeaweedFS with S3 backend and vSphere CSI.
When I try to push an image to the registry both via the Ingress or directly to the Distribution service (via port-forward) I get an error.
My docker client uploads each layer but it looks like on the last chunk of data the upload fails on the server side and hence the docker client retries the layer.
On the server I see some "Unexpected EOF" errors as well as "unknown error" with message "client disconnected during blob PATCH".
There are no errors on the Seaweed FS side.

There are couple of interesting logs in the distribution pod:

time="2025-02-27T11:39:49.80347991Z" level=error msg="client disconnected during blob PATCH" contentLength=-1 copied=11562334 environment=development error="unexpected EOF" 
...
time="2025-02-27T11:39:49.804816224Z" level=error msg="response completed with error" environment=development err.code=unknown err.detail="client disconnected" err.message="unknown error" 
...

Full log file is attached: [logs.txt](https://github.com/user-attachments/files/19009581/logs.txt)

https://github.com/user-attachments/assets/491efe31-98d1-43b8-8bf2-ceb3b017957c

Any advise will be appreciated!

### Reproduce

1. Spin up a k8s cluster (I am reproducing this with both vSphere TKGs and TKGi)
2. Deploy SeaweedFS and configure it with S3 backend. I'm using vSphere CSI as StorageClass
3. Deploy Distribution with the following config:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: ghcr.io/distribution/distribution:edge
          ports:
            - containerPort: 5000
          env:
          - name: REGISTRY_LOG_LEVEL
            value: debug
          - name: REGISTRY_STORAGE_S3_ACCESSKEY
            valueFrom:
              secretKeyRef:
                key: admin_access_key_id
                name: seaweedfs-s3-auth
          - name: REGISTRY_STORAGE_S3_SECRETKEY
            valueFrom:
              secretKeyRef:
                key: admin_secret_access_key
                name: seaweedfs-s3-auth
          - name: REGISTRY_STORAGE
            value: s3
          - name: REGISTRY_STORAGE_S3_REGION
            value: us-east-1
          - name: REGISTRY_STORAGE_S3_ROOTDIRECTORY
            value: /registry
          - name: REGISTRY_STORAGE_S3_BUCKET
            value: registry-bucket
          - name: REGISTRY_STORAGE_S3_REGIONENDPOINT
            value: http://seaweedfs-s3.default.svc.cluster.local:8333
          - name: REGISTRY_STORAGE_S3_ENCRYPT
            value: "false"
          - name: REGISTRY_STORAGE_S3_SECURE
            value: "false"
          - name: REGISTRY_STORAGE_S3_FORCEPATHSTYLE
            value: "true"
          - name: OTEL_TRACES_EXPORTER
            value: "none"
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: default
spec:
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
```

4. Attempt to push an image to the registry

### registry version

Reproducible with both 2.8.3 and 3.0.0-rc3

Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:47 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

### Additional Info

Pushing files directly to SeaweedFS in the same storage bucket via aws-cli is working as expected.
