### ISSUE TITLE
Pull through cache - Add bandwith limitation feature

### ISSUE THREAD

**Issue by SimHeb** [distribution/distribution#4598]
### Description

When using the `distribution` registry in the pull through cache configuration, a `docker pull mirror.company.example/alpine` will cause the local mirror to pull the image from the central repository without any bandwith limitations. Especially for highly decentralised edge locations, where the distribution image can be used as a pull through cache, a bandwith limitation would help to establish a load management for the central instance.

Ideally, the bandwith limitation feature can be configured within the already existing configuration, next to the authentication:

```
proxy:
  remoteurl: https://registry-1.docker.io
  username: [username]
  password: [password]
  pullbandwith: 200m
  ttl: 168h
```
