### ISSUE TITLE
Proxy mode with S3 storage makes 5 requests to S3 per blob when cache is disabled

### ISSUE THREAD

**Issue by kemko** [distribution/distribution#4599]
### Description

When using distribution in proxy mode with S3 storage and caching disabled, the registry makes 5 S3 requests for each blob request instead of a single request. This causes unnecessary load on the S3 backend and potentially increases costs and latency.

### Reproduce

1. Configure distribution with S3 storage and proxy mode (without cache):
   ```yaml
   version: 0.1
   storage:
     s3:
       [S3 configuration details]
   proxy:
     remoteurl: https://something-proxied-registry/
   ```
2.	Configure S3 to work over HTTP for easier debugging
3.	Start tcpdump to monitor HTTP requests: ⁠tcpdump -i any -n port 80
4.	Run ⁠docker pull localhost:5000/someimage:sometag
5.	Observe in tcpdump output that for each blob request, 5 separate S3 requests are made

### Expected behavior

For each blob request to the registry in proxy mode with S3 storage, only a single S3 request should be made when retrieving the blob.

### registry version

v3.0.0-rc.3
