### ISSUE TITLE
docker image files will not be deleted (garbage collector bug?)

### ISSUE THREAD

**Issue by PatrickPromitzer** [distribution/distribution#4607]
### Description

After uploading a docker image and deleting everything image related from the registry, the files still exists.
Adding the setting STORAGE_MAINTENANCE_UPLOADPURGING_AGE to 1h and STORAGE_MAINTENANCE_UPLOADPURGING_INTERVAL to 1h doesn't work.

### Reproduce

Docker compose file:
```
version: '3.8'

services:
  registry-ui:
    image: joxit/docker-registry-ui:main
    restart: always
    ports:
      - 8100:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry-server:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    container_name: registry-ui

  registry-server:
    image: registry:2.8.3 # 2.8.3
    restart: always
    ports:
      - 5000:5000
    environment: # https://distribution.github.io/distribution/about/configuration/
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: '[http://registry-ui.example.com]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: '[HEAD,GET,OPTIONS,DELETE]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: '[true]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: '[Authorization,Accept,Cache-Control]'
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: '[Docker-Content-Digest]'
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      #REGISTRY_STORAGE_MAINTENANCE_UPLOADPURGING_ENABLED: 'true'
      #REGISTRY_STORAGE_MAINTENANCE_UPLOADPURGING_AGE: '1h'
      #REGISTRY_STORAGE_MAINTENANCE_UPLOADPURGING_INTERVAL: '1h'
      #REGISTRY_STORAGE_MAINTENANCE_UPLOADPURGING_DRYRUN: 'false'
      #REGISTRY_STORAGE_MAINTENANCE_READONLY_ENABLE: 'false'
      REGISTRY_STORAGE_MAINTENANCE: |-
        uploadpurging:
            enabled: true
            age: 1h
            interval: 1h
            dryrun: false
        readonly:
            enabled: false

    volumes:
      - docker-registry:/var/lib/registry
    container_name: registry-server

volumes:
  docker-registry:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/patrickpromitzer/temp/docker/docker-registry-data #change this path
```
change the volume path to an existing empty folder.

1.) start docker container
2.) upload docker images

```
docker pull python:3.8 
docker tag python:3.8 127.0.0.1:5000/python:3.8
docker push 127.0.0.1:5000/python:3.8
```
```
docker pull ubuntu:20.04
docker tag ubuntu:20.04 127.0.0.1:5000/ubuntu:20.04
docker push 127.0.0.1:5000/ubuntu:20.04
```
3.) check folder size
![Image](https://github.com/user-attachments/assets/ee21730b-3366-46ad-9fb5-cf4806f0e38e)

4.) delete images on server
```python
import requests
def delete_image_from_server():
    server_url = "http://127.0.0.1:5000"
    images_to_delete =[
        {
            "image_name": "ubuntu",
            "image_tag": "20.04"
        },
        {
            "image_name": "python",
            "image_tag": "3.8"
        },
    ]
    for image_data in images_to_delete:
        image_name = image_data["image_name"]
        image_tag = image_data["image_tag"]
        url = f"{server_url}/v2/{image_name}/manifests/{image_tag}"
        headers = {
            "Accept": "application/vnd.docker.distribution.manifest.v2+json"
        }
        response = requests.get(url, headers=headers)
        response_json = response.json()
        for layer_item in response_json["layers"]:
            layer_url = f"{server_url}/v2/{image_name}/blobs/{layer_item['digest']}"
            print(layer_url)
            response = requests.delete(layer_url)
            print(response)
        response = requests.delete(url, headers=headers)
        print(response)


if __name__ == "__main__":
    delete_image_from_server()
```

5.) check folder size after 2 hours (or later)
![Image](https://github.com/user-attachments/assets/763fcdc8-cb33-45c1-9e02-f04f4f9c1499)

### Expected behavior

The docker image files getting deleted instantly or after the uploadpurging interval. (setting dependence)

### registry version

- registry:2.8.3
